doc/adr/0001-record-architecture-decisions.md
doc/adr/0002-deployment-platform.md
doc/adr/0003-programming-framework.md
doc/adr/0004-default-database.md

Initial ADRs

---

doc/adr/0005-infrastructure-as-code-tool.md

ADR for using ARM templates for IaC

---

doc/adr/0006-dashboard-app-playform.md

ADR for using App Service

---

doc/iac.md
iac/arm-templates/blob-storage.json
iac/create-resources.sh
iac/states.csv

Addresses #6 – barebones implementation; does not address authentication, network restrictions, private networks, etc.

ARM template, script for creating per-state blob storage

---

doc/bulk-import.md
doc/csv/example.csv
doc/csv/import-schema.json
doc/csv/validate.py

Add schema/docs for initial bulk import CSV format

---

ddl/per-state.sql

Initial DDL for per-state logical databases

---

iac/arm-templates/blob-storage.json
iac/arm-templates/key-vault.json
iac/arm-templates/participant-records.json
iac/create-resources.bash

Tag resources with Project=piipan

---

iac/arm-templates/dashboard-app.json
iac/create-resources.bash

Closes #15. Barebones implementation without addressing API, code deployment, networking, etc.

ARM template for dashboard app services

---

doc/adr/0008-use-xunit-net-for-unit-testing.md

ADR for using xUnit unit testing framework

---

doc/ci-cd.md

Closes #114 by documenting manual Snyk config and automated GitHub PR #116

Add note on Snyk/Dependabot

---

.circleci/config.yml
etl/src/Piipan.Etl/BulkUpload.cs
etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/tests/Piipan.Etl.Tests/.vscode/launch.json
etl/tests/Piipan.Etl.Tests/.vscode/tasks.json
etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj

Initial etl tests

---

etl/src/Piipan.Etl/BulkUpload.cs
etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs

- Reactor system under test to permit dependency injection of database
- 98% code coverage, though probably not worth the effort. Better to get 90%+ coverage through functional testing (i.e., with real PostgreSQL instance, etc.).

Complete automated unit testing of etl code

---

README.md

Add CircleCI and Code Climate badges

---

doc/source-guidelines.md
tools/omnisharp.json

Initial guidelines for Piipan .NET source trees

---

README.md
dashboard/README.md
doc/README.md
etl/README.md
iac/README.md
match/README.md

Flesh out top-level README, index and link docs

---

ddl/apply-ddl.bash
ddl/per-state.sql
etl/docs/etl.md
iac/create-resources.bash
match/docs/state-match.md

 Script to create tables in per-state databases

---

etl/docs/bulk-import.md

Link to table schema docs 404'ed. This may be the intended link.

fix broken link to docs

---

etl/src/Piipan.Etl/BulkUpload.cs
etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs
etl/tests/Piipan.Etl.Tests/packages.lock.json
iac/create-resources.bash

Partially addresses #150 – blob access via managed identities in separate PR.

Use managed identities in BulkUpload

---

match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json

Bump dependencies flagged by dependabot in #218 and #217.

Bump dependencies (FluentValidation)

---

docs/adr/0009-continue-to-use-net-core-3-1.md
etl/docs/etl.md
match/docs/state-match.md

Clarify use of .NET Core 3.1 for Piipan

---

docs/adr/0011-use-razor-pages-for-web-apps.md

Closes #57 –  retroactively documenting the Razor Pages decision we made a couple of months ago

ADR for Razor Pages

---

match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/Piipan.Match.Orchestrator.Tests.csproj
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json

Update dependencies for Piipan.Match.Orchestrator

---

match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json

Update FluentValidation dependency

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json

Update AppAuthentication dependency

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/packages.lock.json

Update Microsoft.Azure.WebJobs.Extensions.Storage dependency

---

query-tool/src/Piipan.QueryTool/Pages/Index.cshtml
query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs
query-tool/src/Piipan.QueryTool/PiiRecord.cs

- Adds built-in server-side form validation for the query tool webapp
- Displays validation errors using the USWDS alert component
Currently, all fields are required: 
And formatting for SSN & DOB need to match the API's formatting:

feat: Add basic server-side form validation

---

docs/iac.md
iac/create-metrics-resources.bash
iac/create-resources.bash

- Now that we are deploying to 2 different cloud environments, show how to choose between Azure commercial and Azure government.
- Incorporate metrics resources into the top-level IaC script
- Add a script completed status message to metrics IaC script

Enhance IaC scripts, doc

---

iac/create-metrics-resources.bash

Basic refactor in anticipation of adding command line arguments in a future PR. It looks like almost every line is changed, but ignore white space to hide the noise.

Wrap create-metrics-resources in a main function

---

iac/create-resources.bash

Will be easier to review with ignore white space option, but since I wanted to avoid nested functions in bash, there's a lot of line changes for that required code move.

Wrap create-resources in a main function

---

query-tool/src/Piipan.QueryTool/OrchestratorApiRequest.cs
query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs
query-tool/src/Piipan.QueryTool/Piipan.QueryTool.csproj
query-tool/src/Piipan.QueryTool/Startup.cs
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/IndexTest.cs
query-tool/tests/Piipan.QueryTool.Tests/OrchestratorApiRequestTest.cs
query-tool/tests/Piipan.QueryTool.Tests/Piipan.QueryTool.Tests.csproj
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json

Integrate an `AuthorizedJsonApiClient` into the Query Tool

feat: Add authentication to Query Tool

---

iac/arm-templates/blob-storage.json
iac/arm-templates/function-storage.json
iac/create-resources.bash

Externalize hard-coded location in ARM templates

---

query-tool/src/Piipan.QueryTool/OrchestratorApiRequest.cs
query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs
query-tool/tests/Piipan.QueryTool.Tests/OrchestratorApiRequestTest.cs

Along the way to implementing #478, this PR just ensures something is being logged so I can configure logging in the Azure portal.

Add log statements to query tool

---

.circleci/config.yml
docs/ci-cd.md

Update CircleCI docs and deployment details

---

dashboard/src/Piipan.Dashboard/Pages/Index.cshtml
dashboard/src/Piipan.Dashboard/Pages/Shared/_Layout.cshtml
dashboard/src/Piipan.Dashboard/Pages/Shared/_UsaBanner.cshtml

Nothing fancy. Just added in the .gov banner and some extra USWDS chrome around the `@RenderBody`

Add USA banner & additional templating

---

match/docs/openapi/schemas/match-query.yaml
match/docs/openapi/schemas/pii-record.yaml

add match id as spec to open api docs for orchestrator

---

match/README.md
match/docs/lookup.md
match/docs/openapi/lookup/index.yaml
match/docs/openapi/schemas/lookup.yaml

Add OpenApi schema for Match ID Lookup API with docs scaffold

---

docs/iac.md
iac/arm-templates/function-state-match.json
iac/create-resources.bash
match/src/Piipan.Match.State/Api.cs

Use same approach as in ETL BulkUpload. Code is essentially duplicated from PR #500; defer refactor to #192.

Adapt PerStateMatchApi for AzureUSGovernment

---

tools/update-packages.bash

Small tweak per conversation in #516.

Sort project paths in `update-packages`

---

match/docs/state-match.md

Add remote testing section to state match API documentation

---

dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml.cs
dashboard/tests/Piipan.Dashboard.Tests/ParticipantUploadsModelTests.cs

Adding some logging to the dashboard, just like the query tool got in #494.

Add logging to dashboard app

---

.circleci/config.yml

Fixes deploy [build](https://app.circleci.com/pipelines/github/18F/piipan/743/workflows/fe60581c-6bb6-458b-812b-8b9d6b2b93b2/jobs/1668)

fix typo in circle config

---

dashboard/src/Piipan.Dashboard/Pages/Shared/_Layout.cshtml

Just noticed this title looks sort of confusing when you're presenting:

switch title of dashboard from QueryTool to Dashboard

---

dashboard/dashboard.sln
docs/solution-files.md
etl/etl.sln
match/match.sln
metrics/metrics.sln
query-tool/query-tool.sln

Addresses #157 
- 1 sln per subsystem
- subsystem sln includes test projects

Add solution files for each subsystem

---

match/README.md
match/docs/public-api.md

Closes #556 and final step of #28.

Initial documentation for APIM

---

etl/docs/bulk-import.md
etl/docs/uploads.md

Add documentation for how to upload csv files to Azure Blob storage

---

query-tool/src/Piipan.QueryTool/Pages/Index.cshtml

Change "dual enrollments" to "SNAP participants" in Query Tool

---

match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json

Update state match dependencies

---

.circleci/config.yml

Changed the name of query tool app in iac so had to change it in deployment too

update query tool name in deployment

---

tools/update-packages.bash

- First restore all projects
- Then update all projects
- Finally force-restore all projects
This update fixes the occasional issues we've seen with `update-packages` missing updates or erroring out. Running three operations one-by-one against all packages avoids issues with out-of-sync lock files and transient dependencies being missed depending on the ordering of `find`.

Change order of operations for updating packages

---

docs/openapi/duplicate-participation-api.yaml
docs/openapi/generated/duplicate-participation-api/openapi.md
docs/openapi/generated/duplicate-participation-api/openapi.yaml
docs/quick-start-guide-states.md
etl/docs/openapi/openapi.yaml
etl/docs/openapi/upload.yaml

Include Bulk Upload API in Duplicate Participation API schema

---

docs/openapi/generated/duplicate-participation-api/openapi.md
docs/openapi/generated/duplicate-participation-api/openapi.yaml
docs/quick-start-guide-states.md

- Updates link to bulk upload docs
- Re-generates docs (which I forgot to do in last PR)
- makes some capitalization tweaks

State Guide Refinement Part 2

---

docs/azure-naming-conventions.md

Use staging/stage to refer to the pre-production environment, rather than `preprod`.

Swap in stage for preprod

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json

Major version update; let's see if anything breaks.

Updating CsvHelper to 27.0.0

---

query-tool/src/Piipan.QueryTool/Lookup.cs
query-tool/src/Piipan.QueryTool/ModelBinders.cs
query-tool/src/Piipan.QueryTool/Startup.cs
query-tool/tests/Piipan.QueryTool.Tests/TrimBinderTests.cs

Validate lookup ID input

---

ddl/apply-ddl.bash
docs/iac.md
iac/add-front-door-to-app.bash
iac/arm-templates/blob-storage.json
iac/arm-templates/function-orch-match.json
iac/arm-templates/participant-records.json
iac/create-apim.bash
iac/create-databases.bash
iac/create-metrics-resources.bash
iac/create-resources.bash
iac/iac-common.bash
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/BulkUploadMetrics.cs
metrics/tests/Piipan.Metrics.Tests/BulkUploadMetricsTests.cs

Finalize naming of Azure resources in iac

---

docs/adr/0013-use-private-links.md
docs/securing-internal-apis.md

Add ADR about Azure private link use

---

etl/docs/api.md
match/docs/duplicate-participation-api.md

Closes #639 for now — will readdress if/when source directories are combined into larger groupings (according to our approach to resource groups).

Clarify API documentation and update with new bulk upload approach

---

iac/configure-easy-auth.bash

Wait a bit so newly created AAD SP is queryable

---

docs/openapi/generated/duplicate-participation-api/openapi.md
docs/openapi/generated/duplicate-participation-api/openapi.yaml
iac/arm-templates/apim.json
match/docs/openapi/orchestrator/query.yaml
match/docs/openapi/state/index.yaml

Update documentation to note that the matches only require last name to be an exact match along with DOB + SSN

Correct docs - match on last name only

---

query-tool/src/Piipan.QueryTool/PiiRecord.cs

Per @erinzstrenio's ask
Screenshot:

make query tool form labels sentence case

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/Piipan.Match.State.IntegrationTests.csproj
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/Piipan.Match.State.Tests.csproj
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/Piipan.Metrics.Tests.csproj
metrics/tests/Piipan.Metrics.Tests/packages.lock.json

Update Npgsql and Microsoft.Extensions.Http

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/packages.lock.json

Ran into a small issue with the updated `update-packages` — I'll post a fix in a separate PR.

Update Microsoft.NET.Sdk.Funtions and Azure.Identity

---

query-tool/src/Piipan.QueryTool/Pages/Shared/_LookupResultTable.cshtml
query-tool/src/Piipan.QueryTool/Pages/Shared/_ResultsTable.cshtml
query-tool/src/Piipan.QueryTool/PiiRecord.cs

Remove time from DOB display in query tool UI

---

.github/dependabot.yml

@kingcomma Great idea about dependabot config. Let's see if this will do it in future.

Explicitly add npm to dependabot config for apps

---

docs/adr/0014-durable-functions-for-bulk-matching.md

Marking this as "proposed" rather than "accepted" since we're pausing work on implementation for a few sprints and may have more to add once work resumes. Happy to change if that doesn't feel like the right use of statuses.
Closed #637

Add ADR for bulk match research

---

README.md

Fix incorrect use of the term "passive match"

Swap in "bulk" for "passive"

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json

Update CsvHelper dependency

---

ddl/per-state.sql
etl/docs/csv/example.csv
etl/docs/csv/import-schema.json
etl/src/Piipan.Etl/BulkUpload.cs
etl/src/Piipan.Etl/PiiRecord.cs
etl/src/Piipan.Etl/PiiRecordMap.cs
etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs
iac/create-metrics-resources.bash
iac/create-resources.bash

Closes #597
- both columns are strings
- case id is required, participant id is not

Add case id and participant id to bulk uploaded data

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json

Bump CsvHelper

---

docs/openapi/generated/duplicate-participation-api/openapi.md
docs/openapi/generated/duplicate-participation-api/openapi.yaml
etl/docs/csv/import-schema.json
match/docs/openapi/schemas/pii-record.yaml
match/src/Piipan.Match.Orchestrator/MatchResponse.cs
match/src/Piipan.Match.State/Api.cs
match/src/Piipan.Match.State/MatchResponse.cs
match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs
match/tests/Piipan.Match.State.IntegrationTests/ApiIntegrationTests.cs
match/tests/Piipan.Match.State.IntegrationTests/DbFixture.cs
match/tests/Piipan.Match.State.Tests/ApiModelTests.cs
query-tool/src/Piipan.QueryTool/Pages/Shared/_ResultsTable.cshtml
query-tool/src/Piipan.QueryTool/PiiRecord.cs

Add case id and participant id to match query response and query tool response table

---

dashboard/tests/Piipan.Dashboard.Tests/Piipan.Dashboard.Tests.csproj
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/Piipan.Match.Orchestrator.Tests.csproj
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/Piipan.Match.State.IntegrationTests.csproj
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/Piipan.Match.State.Tests.csproj
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/Piipan.Metrics.Tests.csproj
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/Piipan.QueryTool.Tests.csproj
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump Microsoft.NET.Test.Sdk

---

etl/docs/csv/example.csv
etl/docs/csv/import-schema.json
etl/src/Piipan.Etl/PiiRecordMap.cs
etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs

Remove whitespace from csv column headers

---

iac/arm-templates/function-orch-match.json
iac/arm-templates/function-state-match.json
iac/create-resources.bash

Includes orchestrator and per-state Function Apps

Stream match Function App logs to event hub

---

match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json

Bump FluentValidation

---

iac/arm-templates/dashboard-app.json
iac/arm-templates/query-tool-app.json
iac/create-metrics-resources.bash
iac/create-resources.bash

- Query tool
- Metrics dashboard
Partially addresses #729.

Stream app service logs to event hub

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump FluentValidation, Azure.Core, Microsoft.NET.Sdk.Functions

---

iac/create-metrics-resources.bash

Uses existing CLI-based configuration approach.
There has been some change in the available log categories over the past several days, and this work may need to be updated to include new/changed categories at some point in the future.
Partially addresses #969.

Stream logs for metrics Functions to Event Hub

---

iac/create-resources.bash

Same CLI-based approach as #1015.
Closes #969.

Stream ETL Function logs to Event Hub

---

ddl/per-state.sql
etl/docs/csv/example.csv
etl/docs/csv/import-schema.json
etl/src/Piipan.Etl/BulkUpload.cs
etl/src/Piipan.Etl/Converters.cs
etl/src/Piipan.Etl/PiiRecord.cs
etl/src/Piipan.Etl/PiiRecordMap.cs
etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs
etl/tests/Piipan.Etl.Tests/packages.lock.json
shared/src/Piipan.Shared/MonthEndDateTime.cs
shared/tests/Piipan.Shared.Tests/MonthEndDateTimeTests.cs

Closes #861 
See discussion in #897 on making this table column an array of dates. 
- Since this changes the database schema, I'll drop the participants db server and re-run iac on tts/dev before merging

Add recent benefit months to bulk upload

---

docs/engineering-team-practices.md

Updating which branch we rebase off of in our Engineering Team Practices doc.

switch rebasing branch in docs

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/Piipan.Match.State.IntegrationTests.csproj
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/Piipan.Match.State.Tests.csproj
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/Piipan.Metrics.Tests.csproj
metrics/tests/Piipan.Metrics.Tests/packages.lock.json

Bump Npgsql to 5.0.7

---

metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/packages.lock.json

Bump Azure.Security.KeyVault.Secrets to 4.2.0

---

.circleci/config.yml

Should fix our deploy failures.
Closes #1085.

Update Azure CLI orb to version 1.2.0

---

iac/arm-templates/event-hub-monitoring.json
iac/create-resources.bash
iac/env/tts/dev.bash
iac/env/tts/test.bash

- Add env-specific `$SIEM_RECEIVER` variable to tts/dev and tts/test
- Create app registration if it does not already exist (avoid resetting password on existing registration)
- Assign relevant role to receiver in event hub ARM template
Closes #1064

Create Event Hub log receiver and assign role in IaC

---

metrics/src/Piipan.Metrics/Piipan.Metrics.Api/GetParticipantUploads.cs

Setting the stage for using `Piipan.Shared.Authentication.AuthorizedJsonApiClient` which expects a content type of `application/json`. The metrics API currently returns content type `text/plain`.
An alternative was making `AuthorizedJsonApiClient` more flexible by dropping the explicit `Accept` header, but I'm assuming we'd have eventually wanted the metrics API to return `application/json`.
OmniSharp caught some formatting changes on save.

Return application/json content type from Metrics API

---

docs/log-streaming.md

Document approach to log streaming

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json

Bump csvhelper to 27.1.1

---

dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.Shared/packages.lock.json
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump Azure.Core to 1.16.0

---

match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.State/Piipan.Match.State.csproj
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json

Bump FluentValidation to 10.3.0

---

match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json

Bump Microsoft.Extensions.Http to 3.1.17

---

dashboard/tests/Piipan.Dashboard.Tests/Piipan.Dashboard.Tests.csproj
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/Piipan.Match.Orchestrator.Tests.csproj
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/Piipan.Match.State.IntegrationTests.csproj
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/Piipan.Match.State.Tests.csproj
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/Piipan.Metrics.Tests.csproj
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/Piipan.QueryTool.Tests.csproj
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump coverlet.collector to 3.1.0

---

docs/adr/0017-securing-event-grid-event-handlers.md

As [discussed](https://github.com/18F/piipan/issues/1111#issuecomment-885170735), adds an ADR detailing our current approach to securing Function app event handlers.
Closes #1111.

Add ADR for Event Grid event handlers

---

iac/arm-templates/activity-log.json

Stream `Security` log category to Event Hub

---

dashboard/src/Piipan.Dashboard/appsettings.tts.json

Adds missing `appsettings` file that was left out of #1241

Add missing appsettings.tts.json to Dashboard app

---

dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.Shared/packages.lock.json
match/src/Piipan.Match.State/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump Azure.Core to 1.17.0, Azure.Identity to 1.4.1

---

tools/update-packages.bash

Fixes #1304 
`dotnet list package` will throw a System.ArgumentException if it is passed an empty string as an argument. To address this and avoid a shellcheck conformance flag, use arrays to build up the option string. But implement it so that there is always at least one value in the option array to avoid [this issue in versions of bash < 4.4](https://stackoverflow.com/a/61551944).
Apply a similar technique to other places in the code for consistency and to just avoid passing empty arguments where none should be present.

Fix call to dotnet list package

---

dashboard/tests/Piipan.Dashboard.Tests/Piipan.Dashboard.Tests.csproj
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/Piipan.Match.Orchestrator.Tests.csproj
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
match/tests/Piipan.Match.State.IntegrationTests/Piipan.Match.State.IntegrationTests.csproj
match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.State.Tests/Piipan.Match.State.Tests.csproj
match/tests/Piipan.Match.State.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/Piipan.Metrics.Tests.csproj
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/Piipan.QueryTool.Tests.csproj
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump Microsoft.NET.Test.Sdk to 16.11.0

---

docs/releases.md

This is the process I've been following so far, but feel free to correct/adjust/suggest. Thanks!

Initial release instructions

---

docs/quick-start-guide-states.md

Update quick start guide to use new matching endpoint

---

dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.IntegrationTests/Piipan.Etl.IntegrationTests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.Shared/packages.lock.json
match/tests/Piipan.Match.Orchestrator.IntegrationTests/Piipan.Match.Orchestrator.IntegrationTests.csproj
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump Azure.Core from 1.18.0 to 1.19.0

---

docs/openapi/duplicate-participation-api.yaml
docs/openapi/generated/duplicate-participation-api/openapi.md
docs/openapi/generated/duplicate-participation-api/openapi.yaml
match/docs/openapi/orchestrator/index.yaml

Bump version in duplicate participation API docs

---

docs/quick-start-guide-states.md
etl/docs/csv/plaintext-example.csv

Updating quickstart guide for PPRL approach

---

docs/roadmap.md

Add roadmap to repo documentation

---

dashboard/src/Piipan.Dashboard/Piipan.Dashboard.csproj
dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
etl/tests/Piipan.Etl.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.Shared/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/Piipan.Match.Orchestrator.Tests.csproj
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Tests/Piipan.Metrics.Tests.csproj
metrics/tests/Piipan.Metrics.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/Piipan.QueryTool.csproj
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/Piipan.QueryTool.Tests.csproj
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump .NET dependencies

---

docs/adr/0019-continue-to-use-net-core-3-1.md

Closes #1231 
Adds an ADR for our decision to continue with .NET Core 3.1

Add ADR for continuing with .NET Core 3.1

---

etl/tools/test-apim-upload-api.bash

Missed this when reviewing #1662.

Use current working directory in bulk upload test script

---

docs/openapi/duplicate-participation-api.yaml
iac/apim-duppart-policy.xml
iac/arm-templates/apim.json
match/docs/duplicate-participation-api.md
match/docs/openapi/orchestrator/find.yaml
match/docs/openapi/schemas/match-query.yaml

Derive state name from APIM subscription and send to DupPart API

---

etl/src/Piipan.Etl/Piipan.Etl.csproj
etl/src/Piipan.Etl/packages.lock.json
etl/tests/Piipan.Etl.Tests/packages.lock.json

Bump Microsoft.Azure.WebJobs.Extensions.Storage to 4.0.5

---

metrics/tools/test-metricsapi.bash

Use correct domain if public or government cloud for test-metricsapi.bash

---

tools/authorize-cli.bash

Use the correct domain for gov or public cloud for authorize-cli.bash

---

dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/Piipan.Etl.Func.BulkUpload.csproj
etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/packages.lock.json
etl/tests/Piipan.Etl.Func.BulkUpload.Tests/packages.lock.json
match/src/Piipan.Match.Orchestrator/packages.lock.json
match/src/Piipan.Match.Shared/packages.lock.json
match/tests/Piipan.Match.Core.Tests/Piipan.Match.Core.Tests.csproj
match/tests/Piipan.Match.Core.Tests/packages.lock.json
match/tests/Piipan.Match.Func.Api.Tests/Piipan.Match.Func.Api.Tests.csproj
match/tests/Piipan.Match.Func.Api.Tests/packages.lock.json
match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Core.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Func.Api.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Func.Collect.Tests/packages.lock.json
participants/tests/Piipan.Participants.Core.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump dependencies

---

dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/packages.lock.json
etl/tests/Piipan.Etl.Func.BulkUpload.Tests/packages.lock.json
match/src/Piipan.Match/Piipan.Match.Core/packages.lock.json
match/src/Piipan.Match/Piipan.Match.Func.Api/packages.lock.json
match/tests/Piipan.Match.Core.IntegrationTests/Piipan.Match.Core.IntegrationTests.csproj
match/tests/Piipan.Match.Core.Tests/packages.lock.json
match/tests/Piipan.Match.Func.Api.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Core.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Func.Api.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Func.Collect.Tests/packages.lock.json
participants/tests/Piipan.Participants.Core.Tests/packages.lock.json
query-tool/src/Piipan.QueryTool/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json
shared/src/Piipan.Shared/Piipan.Shared.csproj
shared/src/Piipan.Shared/packages.lock.json
shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj
shared/tests/Piipan.Shared.Tests/packages.lock.json

Bump Azure.Core to 1.20.0

---

iac/create-resources.bash

Update Orchestrator app path in IaC

---

wiki/NAC project overview

Create NAC project overview Wiki content

Create NAC project overview

---

match/tools/test-apim-match-api.bash

Update APIM test script with active example hash

---

match/src/Piipan.Match/Piipan.Match.Core/Piipan.Match.Core.csproj
match/src/Piipan.Match/Piipan.Match.Core/packages.lock.json
match/src/Piipan.Match/Piipan.Match.Func.Api/Piipan.Match.Func.Api.csproj
match/src/Piipan.Match/Piipan.Match.Func.Api/packages.lock.json
match/tests/Piipan.Match.Core.IntegrationTests/Piipan.Match.Core.IntegrationTests.csproj
match/tests/Piipan.Match.Core.Tests/packages.lock.json
match/tests/Piipan.Match.Func.Api.IntegrationTests/Piipan.Match.Func.Api.IntegrationTests.csproj
match/tests/Piipan.Match.Func.Api.Tests/packages.lock.json

Update dapper dependencies to 2.0.123

update dpper dependencies

---

wiki/user.research.md

A couple formatting updates and clarifications, since I want to direct vendors here in response to some of their questions.

Formatting changes for user research

---

.gitignore
iac/Dockerfile

The command that allows installation of extensions was commented.

Fix dockerfile to allow installation of extentions

---

dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Client/Piipan.Metrics.Client.csproj
metrics/tests/Piipan.Metrics.Client.Tests/packages.lock.json

Fix Azure Core version in Piipan.Metrics.Client

---

iac/create-metrics-resources.bash

Add trailing slash to metrics API URI

---

docs/securing-internal-apis.md
iac/configure-easy-auth.bash

Use cloud-specific AAD endpoint when configuring App Service Auth

---

iac/arm-templates/virtual-network.json

Add Microsoft.Storage service endpoint to function apps subnet

---

iac/create-resources.bash

Stream event grid system topic logs to Event Hub

---

docs/engineering-team-practices.md

Update team practicies with details on sprints and releases

---

.gitignore
iac/Dockerfile
iac/create-resources.bash

Added query WAF Custom Rule Polity that matches POST request methods and applies an API Rate Limit, similar to the APIM Rate Limit #2301.
I tested this on `tts/eth` and `tts/dev` the code recreate the rule.

Eth/query tool rate limit. Close #2345

---

docs/iac.md
etl/tools/create-apim-bulk-subscription.bash
match/docs/duplicate-participation-api.md
match/tools/create-apim-match-subscription.bash

- Add script for both DupPart and Bulk APIs
- Update documentation
Closes #1844

Add scripts for creating APIM subscription keys

---

dashboard/docs/dashboard.md
docs/iac.md
query-tool/docs/query-tool.md

- Update local development instructions for Query Tool and Dashboard apps
- Update list of environment variables in IaC docs
Closes #2621 

Document *ApiAppId environment variables

---

CHANGELOG.md

Updating Changelog for v1.0.0.34
Capturing changes from sprint 34.

Update CHANGELOG for v1.0.0.34

---

dashboard/src/Piipan.Dashboard/Piipan.Dashboard.csproj
dashboard/src/Piipan.Dashboard/packages.lock.json
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json

Bumping TimeZoneConverter dependency to 5.0.0

Update TimeZoneConverter dependency to 5.0.0

---

docs/adr/0030-use-blazor-component-library.md

ADR for using a Blazor Component Library
A component library project, under a new "components" folder in the main solution should be created. There are three parts to this project: 
1. The component library itself, which will get included into the other web applications. Named: Piipan.Components
2. A demo project of the component library, where the developers can go and see all of the components and their functionality. Named: Piipan.Components.Demo
3. A test project of the component library, written in [bUnit](https://bunit.dev/), where all of the components can be thoroughly tested. Named: Piipan.Components.Tests
Blazor Components are reusable by design. Simply passing in different parameters to the components allows different behaviors without changing the component at all. We can …

ADR for the Blazor Component Library

---

iac/arm-templates/participant-records.json
iac/create-resources.bash

- Precursor to related application updates
- Increase available IOPS by increasing storage (300GB) on participant records database to improve performance during large writes
- Add several database connection string settings to allow long-running database transactions
Also adds "createMode" property to conform with ARM template schema requirements.
Partially addresses NAC-556

IaC performance enhancements for participant uploads

---

ddl/per-state.sql
participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/UploadDao.cs
participants/tests/Piipan.Participants.Core.IntegrationTests/DbFixture.cs
shared/src/Piipan.Shared.TestFixtures/OrchestratorDbFixture.cs
shared/src/Piipan.Shared.TestFixtures/ParticipantsDbFixture.cs

Adding Status Column to uploads table
needed for tickets nac-414 and nac-416
- [x ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

CJC adding status column to Uploads table

---

iac/add-front-door-to-app.bash
iac/arm-templates/front-door-app-service.json

PR [3147](https://github.com/18F/piipan/pull/3147) had an issue when publishing for the first time, due to this issue:[https://github.com/MicrosoftDocs/azure-docs/issues/61497](https://github.com/MicrosoftDocs/azure-docs/issues/61497)
To get around that issue, we need to create the rules engine initially, but then associate it to the front door routing rule after front door was created.
Follow-up to PR [3147](https://github.com/18F/piipan/pull/3147)

Front door security rules IAC fix

---

components/tests/Piipan.Components.Tests/Piipan.Components.Tests.csproj
dashboard/tests/Piipan.Dashboard.Tests/Piipan.Dashboard.Tests.csproj
dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/Piipan.Etl.Func.BulkUpload.csproj
etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/packages.lock.json
etl/tests/Piipan.Etl.Func.BulkUpload.Tests/packages.lock.json
match/src/Piipan.Match/Piipan.Match.Core/Piipan.Match.Core.csproj
match/src/Piipan.Match/Piipan.Match.Core/packages.lock.json
match/src/Piipan.Match/Piipan.Match.Func.Api/Piipan.Match.Func.Api.csproj
match/src/Piipan.Match/Piipan.Match.Func.Api/packages.lock.json
match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/Piipan.Match.Func.ResolutionApi.csproj
match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/packages.lock.json
match/tests/Piipan.Match.Core.Tests/packages.lock.json
match/tests/Piipan.Match.Func.Api.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.Func.Api.Tests/packages.lock.json
match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/packages.lock.json
match/tests/Piipan.Match.Func.ResolutionApi.Tests/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Api/Piipan.Metrics.Func.Api.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Api/packages.lock.json
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Collect/Piipan.Metrics.Func.Collect.csproj
metrics/src/Piipan.Metrics/Piipan.Metrics.Func.Collect/packages.lock.json
metrics/tests/Piipan.Metrics.Func.Api.Tests/packages.lock.json
metrics/tests/Piipan.Metrics.Func.Collect.Tests/packages.lock.json
query-tool/tests/Piipan.QueryTool.Tests/Piipan.QueryTool.Tests.csproj
query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json

Updating .NET dependencies that Dependabot found
Closes NAC-800

Updating .NET dependencies

---

CHANGELOG.md

Updating changelog for sprint 41
Updating changelog for sprint 41

Updating changelog for sprint 41

---

match/tests/Piipan.Match.Core.Tests/Validators/AddEventRequestValidatorTests.cs

Something didn't merge quite right between @ccaprio97 and my latest PR. This should fix that.

Fixing merge issue

---

CHANGELOG.md

Update changelog for sprint 45
Update changelog for sprint 45

Update changelog for sprint 45

---

iac/env/tts/test/states.csv

* Enable all states in `tts/test` environment
* Add MO to list of states in `tts/test` per request
Closes NAC-1013

Enable all states and add MO in tts/test
