18F/piipan

iac/create-databases.bash, iac/create-resources.bash
- Set up PostgreSQL AD admin group
- Create managed identity for each state
- Create managed roles for each state db
- Grant managed role required privileges
- Managed role will need to use SET ROLE <DBOWNER> to apply schema changes
=> Create per-state managed identities and db roles

.circleci/config.yml
Adjusts `.circleci/config.yml` to include the `test` job in the `requires` list for each deploy job. Fixes an issue with my original implementation that ran the test job but did not require it for before starting a deploy job.
=> Configure CircleCI to require successful testing before deploy

etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj
Since we include Piipan.Etl, don't need to re-specify CSVHelper as a dependency here. Doing so can cause mismatches, Dependabot failures.
=> Remove redundant CSVHelper package

.circleci/config.yml, dashboard/src/Piipan.Dashboard/Piipan.Dashboard.csproj, dashboard/src/Piipan.Dashboard/packages.lock.json, dashboard/tests/Piipan.Dashboard.Tests/Piipan.Dashboard.Tests.csproj, dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json, etl/src/Piipan.Etl/Piipan.Etl.csproj, etl/src/Piipan.Etl/packages.lock.json, etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj, etl/tests/Piipan.Etl.Tests/packages.lock.json
Closes #153.
References:
- [Enable repeatable package restores using a lock file](https://devblogs.microsoft.com/nuget/Enable-repeatable-package-restores-using-a-lock-file/)
- [Using a NuGet Lock File for Reproducible Builds](http://blog.ctaggart.com/2019/03/using-nuget-lock-file-for-reproducible.html)
=> Enable repeatable package restores via lock file

docs/iac.md, iac/create-resources.bash
Partially addresses #150.
For the ETL functions, bind the corresponding database connection string to the function via the DatabaseConnectionString environment variable. The Password placeholder will be replaced at runtime by the ETL function code with the a service token in a follow-on PR.
=> Bind database connection string at provision time

iac/create-resources.bash
Should resolve need to have a local.settings.json file in the working directory when publishing initial Azure function in IaC.
Still need to make similar changes to CI/CD script, etc.
=> Fix local.settings.json error, use --dotnet

iac/arm-templates/function-state-match.json, iac/create-resources.bash, match/docs/state-match.md, match/src/Piipan.Match.State/Api.cs, match/src/Piipan.Match.State/Converters.cs
Adds some follow up work from #168:
- Cleans up documentation
- Removes unneeded `SET ROLE` directive (#198)
- Brings DB connection approach into sync with #199
=> Follow up to initial state match API work

docs/adr/0010-use-bash-for-scripting.md, iac/create-databases.bash, iac/create-resources.bash, iac/create-service-principal.bash, tools/common.bash
- -e flag doesn't on its own work with command substitutions, so several
options were added to allow scripts to always immediately exit on error
- add explicit success message to end of IaC scripts
Foundational work for #243
=> Better script error handling and ADR for scripts

docs/iac.md, iac/.azure/config, iac/create-resources.bash, iac/install-extensions.bash
Closes #243
By default, Azure CLI commands will prompt to install extension libraries as it needs them. This can obscure the dependencies required for our IaC scripts and cause unexpected failures. To resolve this, we:
- add a local Azure CLI configuration to the working directory of the IaC scripts to turn off autodownload of extensions
- provide a script to install prerequisite extensions
- amend documentation to reference additional step
=> Explicitly install required CLI extensions

iac/create-resources.bash, iac/create-service-principal.bash
- Add match API resouce group to CI/CD service principal
- Move invocation of create-service-principal to be closer
to creation of resource groups
=> Update resource group list that CI/CD can update

dashboard/docs/dashboard.md
Since .NET Core 5 was released a couple weeks into this project (after the hello world dashboard was created) and Azure Functions currently only support a max of 3.1.
=> Specify .NET Core version as 3.1 in Dashboard App Docs

docs/iac.md, etl/docs/etl.md, iac/create-resources.bash
Closes #242
- Move blob connection string binding to Function app from manual process to IaC
- Remove manual documentation for setting service bindings
- Update IaC docs to reflect standard environment variable name for blob
connection strings
- Add note about grant-blob taking several minutes to replicate out
=> Automate blob binding, update docs

match/src/Piipan.Match.Orchestrator/MatchResponse.cs, match/src/Piipan.Match.State/Api.cs, match/tests/Piipan.Match.State.Tests/ApiTests.cs
`StateName` and `StateAbbr` in `Piipan.Match.Orchestrator.PiiRecord` were vestiges from previous work on the per-state APIs.
`Piipan.Match.State.Api` no longer used `StateAbbr` or `ServerName` after the database connection mechanism was updated in #210.
=> Remove unused environment variables from match APIs and tests

.circleci/config.yml
The Azure app name & resource group were previously pulled in from CI environment variables. Because this isn't sensitive information, it's easier to just include it directly in the configuration.
=> Hard code app name & resource group

iac/arm-templates/participant-records.json
Closes #299. Allows ETL and state match API to communicate to participatns-db ahead of fully fleshed out VNets, network security groups in our sandbox. Will be reversed in https://github.com/18F/piipan/issues/331
=> Temporarily add AllowAllWindowsAzureIps to db

docs/iac.md, iac/arm-templates/function-orch-match.json, iac/arm-templates/function-state-match.json, iac/create-resources.bash, match/docs/openapi/state/index.yaml, match/docs/orchestrator-match.md, match/docs/state-match.md, match/src/Piipan.Match.Orchestrator/Api.cs, match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj, match/src/Piipan.Match.Orchestrator/packages.lock.json, match/src/Piipan.Match.State/Api.cs, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs, match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json, match/tests/Piipan.Match.State.Tests/ApiTests.cs
Closes #275. Details:
- Enables app service authentication (aka Easy Auth) for the per-state match APIs via IaC
- Creates and assigns an "app role" used to authorize authenticated requests to a state API
- Updates the orchestrator API to obtain and pass Easy Auth bearer tokens when querying a state API
- Updates OpenAPI specs to reference new bearer token requirement
Follow up work will include:
- Minimizing the use of the AZ CLI in our IaC in favor of ARM templates or [deployment scripts](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template) (this update is probably the last straw for the existing IaC script) #101
- Migrating the authentication library used by each API subsystem to `Azure.Identity` #318
- [More meaningful validation of …
=> Implement authentication and authorization between orchestrator and per-state APIs

docs/adr/0012-use-app-service-authentication-between-subsystems.md
This documents the decision to use App Service authentication (aka Easy Auth) to secure our internal APIs. The implementation details of this approach were established in #317.
Closes #322.
=> ADR for App Service authentication

metrics/src/Piipan.Metrics/PiipanMetricsApi/Piipan.Metrics.Api.csproj, metrics/src/Piipan.Metrics/PiipanMetricsApi/packages.lock.json, metrics/tests/Piipan.Metrics.Tests/Piipan.Metrics.Tests.csproj, metrics/tests/Piipan.Metrics.Tests/packages.lock.json
@echappen `Microsoft.Azure.Services.AppAuthentication` was flagged as out of date in `PiipanMetricsApi`, but I think it's unused now that the project uses `Azure.Identity`. I removed the dependency and tests / builds run fine, but would appreciate a look in case I missed anything.
=> Update dependencies, remove AppAuthentication dependency from PiipanMetricsApi

iac/arm-templates/function-orch-match.json, iac/arm-templates/query-tool-app.json, iac/create-resources.bash
This PR partially addresses #281 by declaring the necessary infrastructure for enabling authentication on the orchestrator API and granting permissions to the query tool. Specifically:
- Enables authentication on orchestrator
- Removes IP restriction from orchestrator
- Activates system identity for query tool
- Grants app role to query tool identity
- Moves easy auth activation to reusable `enable_easy_auth` function
Follow on work:
- Implement new authentication flow for the query tool using `Piipan.Shared.Authentication`
- Afterwards, disable the GSA network block that has been temporarily left in place (#331)
=> IaC for authentication between query tool and orchestrator API

query-tool/src/Piipan.QueryTool/Pages/Index.cshtml, query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs
Provide visual feedback to the user that the query completed successfully, but that there were no matches:
=> feat: Display alert when search returns no results

dashboard/src/Piipan.Dashboard/Api/ParticipantUploadRequest.cs, dashboard/src/Piipan.Dashboard/Pages/Index.cshtml, dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml, dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml.cs, dashboard/src/Piipan.Dashboard/ParticipantUpload.cs, dashboard/src/Piipan.Dashboard/Piipan.Dashboard.csproj, dashboard/src/Piipan.Dashboard/Startup.cs, dashboard/src/Piipan.Dashboard/packages.lock.json, dashboard/tests/Piipan.Dashboard.Tests/Api/ParticipantUploadRequestTests.cs, dashboard/tests/Piipan.Dashboard.Tests/IndexPageTest.cs, dashboard/tests/Piipan.Dashboard.Tests/ParticipantUploadsModelTests.cs, dashboard/tests/Piipan.Dashboard.Tests/Piipan.Dashboard.Tests.csproj, dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json, iac/arm-templates/dashboard-app.json, iac/create-metrics-resources.bash, iac/create-resources.bash, iac/iac-common.bash, metrics/src/Piipan.Metrics/PiipanMetricsApi/GetParticipantUploads.cs, metrics/src/Piipan.Metrics/PiipanMetricsApi/Serializers/Meta.cs, metrics/tests/Piipan.Metrics.Tests/PiipanMetricsApiTests/GetParticipantUploads.Tests.cs, metrics/tests/Piipan.Metrics.Tests/PiipanMetricsApiTests/Serializers.Tests/MetaTests.cs
Wanted to try getting this in before our demo tomorrow. This is a completely un-styled version of showing participant upload metrics in the Dashboard app through server-side API requests.
Creates a new Dashboard page and model `ParticipantUploads` which shows:
- list of most recent participant uploads from the etl `BulkUpload` actions
- a search input with a "clear search" button to query by state name
- prev/next page links
Does not have:
- frontend validation for search input
- USWDS styling
I referred a lot to @heymatthenry's work in how to make server-side api requests and how to mock api requests in tests (thanks, Matt).
If you test locally, you need to be on the GSA network in order to make the API request.  
Specifically looking for better ways to test the page models, and to …
=> show participant upload metrics in dashboard

docs/iac.md
Forgot to document the new Environment Variable I added to the Dashboard ARM template.
=> Add metrics api uri env var in iac docs

dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml.cs, dashboard/tests/Piipan.Dashboard.Tests/ParticipantUploadsModelTests.cs
Proof of concept of some basic tests for the Get and Request methods on a page model. Shows how to mock HttpContext so objects like `Request.Query` and `Request.Form` can be manipulated in the tests.
Nothing super specific I'm looking for feedback on here, just interested to hear anyone's general thoughts.
=> Add page model tests to dashboard

iac/arm-templates/metrics.json, iac/create-metrics-resources.bash
Resolves [#338](https://github.com/18F/piipan/issues/388)
Doing this made me realize the virtual network in my metrics.json template was unnecessary. I think this was residual from pulling this example ARM template from Azure docs.
=> Downgrading metrics db to Basic tier with other iac improvements

iac/create-resources.bash, match/docs/orchestrator-match.md, match/src/Piipan.Match.Orchestrator/Startup.cs, shared/src/Piipan.Shared/Authentication.cs, tools/assign-app-role.bash, tools/assign-app-role.sh
Establishes the approach for #425. Specifically:
- Adds CLI-based token provider
- Adds helper script for assigning app roles
- Updates orchestrator to use appropriate token provider for the current configuration
- Documents local development for orchestrator
- Updates IaC to allow app role assignment to users
All of the above has been done in the context of `Piipan.Match.Orchestrator`, but I'm thinking this same approach applies to any Azure resource acting as a client of one of our internal APIs.
Follow-up work:
- Add a helper script for adding the Azure CLI as an authorized client application to an existing application object (requires more research)
=> Add local development approach to orchestrator API

iac/create-metrics-resources.bash, iac/create-resource-groups.bash, iac/create-resources.bash
This will be more important in environments where we do not have permission to create the resource groups ourselves.
=> Move resource group creation to separate script

etl/src/Piipan.Etl/BulkUpload.cs, etl/src/Piipan.Etl/PiiRecordMap.cs, etl/src/Piipan.Etl/Piipan.Etl.csproj, etl/src/Piipan.Etl/packages.lock.json, etl/tests/Piipan.Etl.Tests/Piipan.Etl.Tests.csproj, etl/tests/Piipan.Etl.Tests/packages.lock.json
As noted in #230, `CsvHelper` has undergone quite a bit of churn recently. This PR just updates the library to the most recent version and fixes a handful of issues created by the many breaking changes.
=> Update to most recent CsvHelper version

iac/create-metrics-resources.bash, iac/create-resources.bash
Waiting 60 seconds before publishing a Function to a new Function App has worked well so far, as Azure will report a Function App has been deployed when it actually hasn't fully deployed.
macOS sleep does not support units, so drop the "s" in "60s" on existing sleep uses.
=> Wait a bit before publishing func to new func app

iac/create-metrics-resources.bash
Azure Government regions are quite long (e.g., usgovvirginia) and frequently push resource ids beyond their character count limit. Drop location from all resource ids for consistency.
Partially addresses #101
=> Drop location from metrics resource ids

iac/create-metrics-resources.bash
This also mitigates the need to have commercial/government-specific domain names when accessing Key Vault.
Partially addresses #101
=> Get PostgreSQL password directly vice Key Vault

iac/create-resources.bash
Resolves "Invalid URI: The URI scheme is not valid." error in query tool when it attempts to call out to the orchestrator API endpoint.
=> Don't use double quotes around orch api URI

iac/env/tts/dev.bash
Add `rg-` prefix, drop `piipan` since everything is Piipan, add `-dev` to reflect development deployment. See not-quite-finalized naming standard in PR #451.
Renaming this now since I'm rebuilding everything this evening due to a problem related to [changes in Azure](https://docs.microsoft.com/en-us/azure/app-service/overview#limitations) and making our Azure Government and Azure Commercial spaces consistent:
"However, all resource groups created on or after January 21, 2021 do support [mixing Windows and Linux apps in the same resource group]"
=> Align resource groups with new naming standard

iac/create-resources.bash
Don't create service principal in main IaC because:
- not necessary in all deployment environments
- resets the SP secret every time IaC runs, which requires it to be updated in CircleCI
=> Remove service principal creation from main IaC

docs/iac.md, etl/docs/etl.md, etl/src/Piipan.Etl/BulkUpload.cs, iac/create-resources.bash, iac/iac-common.bash
Commercial and Government Azure use different ossrdbms-aad resource ids; this id needs to be specified when accessing PostgreSQL via a managed identity. Bind the cloud name during infrastructure setup as an environment variable, then use that to choose the right id for the active cloud in the ETL function.
=> Use cloud-specific resource id w/managed identity

iac/create-metrics-resources.bash
Remove the conditional block around assigning identity and Key Vault policy for both Function Apps. The conditional block is only required to workaround an Azure issue setting managed identity multiple times (see create-resources.bash).
This fixes an access control issue where a metrics Function App would be deployed but could not access its database secret; i.e., when there was a partial IaC run with an error, followed by a 2nd complete run.
=> Unconditionally assign identity, set kv policy in metrics IaC

etl/docs/etl.md, etl/tools/grant-blob.bash, etl/tools/upload.bash
By requiring the target azure environment on the CLI, we defensively protect ourselves from running against the wrong account and avoid hard-coding the resource group in the case of grant-blob.
=> Extend ETL dev tools to consult azure env config

iac/add-front-door-to-app.bash, iac/create-metrics-resources.bash, iac/create-resources.bash, iac/iac-common.bash
A few minor tweaks needed to create Front Door instances:
- resolves "web_app_host_suffix: unbound variable" error
- confirms azurefd.us is Azure Government Front Door domain
- echos the return suffix instead of returning; bash functions can only return integers in [0-255] range
=> Fix for creating Azure Front Door instances

iac/create-metrics-resources.bash
Fixes error where the comment inadvertently became part of the command since the command was split across multiple lines via the backslash:
```
UnrecognizedArgumentError: unrecognized arguments:  # LEFT OFF HERE
```
=> Fixes UnrecognizedArgumentError error in metrics IaC

iac/delete-resources.bash
This allows us to test the IaC from a clean slate more easily. It does not remove dangling app registrations in Active Directory.
=> Script to delete resources from resource groups

docs/iac.md, iac/arm-templates/dashboard-app.json, iac/arm-templates/function-orch-match.json, iac/arm-templates/function-state-match.json, iac/arm-templates/query-tool-app.json
This tag is used to ease enumeration of resource instances in IaC and to make a resource's system-level purpose more obvious in the Azure Portal, especially when naming restrictions cause names to be somewhat inscrutable.
=> Add SysTag resource tag to key system components

iac/configure-easy-auth.bash, iac/iac-common.bash
- Use AzureUSGovernment-specific graph API URL
- Add pauses between resource creation and use in a few more places
- Generalize to reduce code duplication
Partially addresses #101
=> Adapt Easy Auth IaC for Azure Government

docs/iac.md, iac/create-metrics-resources.bash, metrics/src/Piipan.Metrics/Piipan.Metrics.Api/GetParticipantUploads.cs, metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/BulkUploadMetrics.cs
Adopt pattern implemented in ETL, per-state match API for Key Vault. Key Vault usage will be eliminated in #409, so not concerned about the duplicated code across `Api` and `Collect`.
=> Adapt metrics subsystem for AzureUSGovernment

docs/iac.md, iac/create-resources.bash
Contributor access is sufficient for setting up Easy Auth after all.
=> Reincorporate Easy Auth config into main IaC

docs/iac.md, iac/arm-templates/apim.json, iac/create-apim.bash, iac/iac-common.bash
First step in creating the API Management (APIM) instance to sit in front of the orchestrator API. Specifically:
- Creates APIM instance from ARM template
- Cleans unused default resources created in the process
This does not create a function API or any publicly accessible resources (other than a "portal" error page at `https://<apim-name>.developer.azure-api.net/`) that seems to be unavoidable at this juncture). This a first step in a series of self-contained PRs for this issue.
I'd especially appreciate feedback on:
- Creating a new APIM instance can take upwards of ~45-50 minutes. Consequently, I've created a `create-apim` script that is intended to be run separately from `create-resources` so developers aren't subjected to that delay on every IaC build.
- APIM instances require a …
=> Create APIM stub for public API

iac/iac-common.bash
Per bash docs, `local myvar=$(subcommand)` will always return 0 so don't use it inline with subcommands. Also: explicitly send error messages to `stderr`.
=> Don't let local silently absorb non-zero exit code

iac/arm-templates/apim.json, iac/create-apim.bash
- Create version set with v1 identifier
- Link API to version set
- Remove unused variables and parameters
Establishes a versioned API which uses a path segment (e.g., `/v1`) to differentiate between versions. Still fleshing out the scaffolding, no publicly-accessible components.
Partially addresses #28.
=> Add versioning to APIM instance

iac/arm-templates/apim.json
Adds initial operation to APIM instance and creates a `/query` endpoint.
Follow up PR will connect this operation to the backend server (orchestrator Function App). Until then, the endpoint is effectively a stub.
The operation is hard-coded in `apim.json` for now, but could be scraped in favor of dynamic creation by importing the OpenAPI spec via the [`value` property on the API resource](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2019-01-01/service/apis?tabs=json#apicreateorupdateproperties-object). This work is described in #548.
=> Add POST operation for matching API query

match/docs/openapi/schemas/match-query.yaml, match/src/Piipan.Match.Orchestrator/MatchRequest.cs, match/src/Piipan.Match.Orchestrator/MatchRequestValidator.cs, match/src/Piipan.Match.State/Api.cs, match/src/Piipan.Match.State/MatchRequest.cs, match/src/Piipan.Match.State/MatchRequestValidator.cs, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs, match/tests/Piipan.Match.State.Tests/ApiTests.cs, query-tool/src/Piipan.QueryTool/PiiRecord.cs
Addresses #528 
* Add validations for first name in Match & Orchestrator APIs
* Remove validation for middle name in Query Tool
=> Require first name in API/Query tool; Don't require middle name

iac/arm-templates/apim.json, iac/configure-easy-auth.bash, iac/create-apim.bash
- Reference orchestrator URL from APIM API resource
- Configure Easy Auth between APIM and orchestrator
Follow on work to #549. Puts the pieces in place to connect the APIM instance to the orchestrator API. Will be followed by a PR that connects the APIM frontend to the orchestrator backend using a managed identity authentication policy.
=> Point APIM to backend service

.circleci/config.yml, iac/arm-templates/dashboard-app.json, iac/arm-templates/front-door-app-service.json, iac/arm-templates/query-tool-app.json, iac/create-metrics-resources.bash, iac/create-resources.bash
Initially, restricting access to only GSA IP's was set on the web apps themselves.
When Azure Front Doors were applied to the apps, this blocked traffic from the Front Door Backends.
Instead, the web apps are now restricted to `AzureFrontDoor.Backend` traffic, and GSA IP restrictions are now set as rules on the related Front Door WAF policies. 
This restricts traffic to the app from everywhere except through the front-door URL when on the GSA network.
This creates a co-dependency when creating web app and front door resources: web apps need the front door ID in order to set the backend restrictions, and front doors need the app host name in order to connect the app to the front door resource.
Consequently, the ARM templates become more reliant on naming conventions. It also becomes more …
=> Fix: move GSA IP restrictions from web app level to Front Door/WAF policy level

match/src/Piipan.Match.State/Api.cs
A trailing space got dropped in a previous commit resulting in a broken SQL query (line 102). OmniSharp picked up an additional formatting tweak upon save.
=> Re-add dropped whitespace in concatenated SQL query

iac/apim-policy.xml, iac/arm-templates/apim.json, iac/create-apim.bash
- Add base XML policy, extended to include managed identity auth
- Update policy with application ID URI when running IaC
- Drop unnecessary subscription key header when forwarding request to
orchestrator API
This is the final piece in creating a working APIM instance for the public API. After the IaC is run, any request with a valid [subscription key](https://docs.microsoft.com/en-us/azure/api-management/api-management-subscriptions) will initiate an API call to the orchestrator API. Specifically:
1. A user/system submits a valid request to the APIM endpoint
2. APIM authenticates with orchestrator API using its system-assigned identity
3. APIM forwards the request to the orchestrator API
4. APIM forwards response from orchestrator API back to user/system
The XML policy is barebones, and …
=> Add APIM policy for Public API

iac/arm-templates/front-door-app-service.json
For simplicity purposes -- this effectively does the same thing as the previous rule to deny all non-GSA IP's
=> Deny all IP addresses as lower-priority firewall rule

match/docs/openapi/lookup/index.yaml, match/tools/generate-specs.bash
Just noticed I didn't include the new lookup api here
=> include lookup api when generating api specs

match/docs/openapi/schemas/match-query.yaml, match/src/Piipan.Match.Orchestrator/MatchResponse.cs
- Update model
- Reflect null potential in spec
Small first step towards #452. Lookup ID generation has not been implemented. All responses will contain a `lookup_id` property with a `null` value. E.g.,
```
{
"lookup_id": null,
"matches": [
{
"last": "Lynn",
"first": "Wesley",
"middle": "Eura",
"ssn": "000-12-3457",
"dob": "1940-08-01",
"exception": null,
"state_name": "Echo Alpha",
"state_abbr": "ea"
}
]
}
```
=> Stub lookup ID into orchestrator response

iac/arm-templates/function-orch-match.json, iac/create-resources.bash
[Azure Table Storage](https://docs.microsoft.com/en-us/azure/storage/tables/table-storage-overview#:~:text=Azure%20Table%20storage%20is%20a,needs%20of%20your%20application%20evolve.) seems like the right initial fit for storing queries that will later be retrieved via the lookup API. This PR modifies the IaC to create the necessary storage account and table resource, and bind the storage account to the orchestrator. Binding is done via a connection string — future work should switch to using shared access signatures (see #213).
Partially addresses #195 and #452.
=> Add Table Storage resource for lookup API

match/src/Piipan.Match.Orchestrator/Api.cs, match/src/Piipan.Match.Orchestrator/Lookup.cs, match/src/Piipan.Match.Orchestrator/MatchRequest.cs, match/tests/Piipan.Match.Orchestrator.Tests/LookupTests.cs
Initial approach for generating a lookup ID:
1. Hashes the query (as a serialized JSON string)
1. Reduces hash to 32 bits (to conform to a 7 character length in our custom alphabet)
1. Encodes using our custom alphabet
1. If necessary, pads the encoded string to ensure a consistent length
**Considerations**:
- The ID is 7 characters rather than 6 (which is specified in the issue's AC #452). 7 characters happens to work nicely with a 32-bit integer, which can be easily derived from the hash using `ToUInt32()`. 6 characters is doable, but increases the chance of collisions and requires a little extra finagling to drop the 32-bit integer to the proper size (29-bits).
- Dropping the hash down to 32 bits (or lower if we go with 6 characters), presumably increases the chance of collision. I'm …
=> Generate lookup ID upon orchestrator match

.github/dependabot.yml, match/src/Piipan.Match.Orchestrator/packages.lock.json, match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json, query-tool/src/Piipan.QueryTool/packages.lock.json, query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json, shared/src/Piipan.Shared/Piipan.Shared.csproj, shared/src/Piipan.Shared/packages.lock.json, shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj, shared/tests/Piipan.Shared.Tests/packages.lock.json
When updating the Azure.Core dependency the projects in `query-tool` were updated despite not being in the list of projects flagged by dependabot's PRs. They were missed because the paths were not in the dependabot config.
This adds the paths to the config and updates Azure.Core in all projects.
=> Update Azure.Core dependency and add query-tool to dependabot

match/src/Piipan.Match.Orchestrator/Api.cs
Make better use of async calls to per-state APIs by handling them concurrently rather than sequentially.
Closes #452
=> Query state APIs concurrently

match/src/Piipan.Match.State/Api.cs, match/tests/Piipan.Match.State.Tests/ApiTests.cs
Updates per-state APIs to ignore middle name when performing match.
To test, follow the [directions to use the duplicate participation API](https://github.com/18F/piipan/blob/main/match/docs/duplicate-participation-api.md#calling-the-api) or submit a request directly to the [orchestrator API](https://github.com/18F/piipan/blob/main/match/docs/orchestrator-match.md#remote-testing). Example.csv has been uploaded to each state with a varying middle name for the `Lynn,Wesley,Eura,8/01/1940,000-12-3457,` row. Submitting a request for, for example:
```
{
"query": {
"last": "Lynn",
"dob": "1940-08-01",
"ssn": "000-12-3457",
"first": "Wesley",
"middle": "E"
}
}
```
Should return the following results (note the differing `middle` property):
```
{
"lookup_id": "...",
"matches": [
{
"last": "Lynn", …
```
=> Update per-state APIs to ignore middle name when performing match

match/src/Piipan.Match.Orchestrator/Api.cs, match/src/Piipan.Match.Orchestrator/Lookup.cs, match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj, match/src/Piipan.Match.Orchestrator/packages.lock.json, match/tests/Piipan.Match.Orchestrator.Tests/LookupTests.cs, match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
Per conversation in #604, switches lookup ID to be a randomly generated 7-character string that conforms to our custom alphabet.
Uses the C# implementation of Nanoid (a popular [JavaScript tool](https://www.npmjs.com/package/nanoid)).
=> Switch to randomly generated lookup ID

docs/iac.md, match/docs/orchestrator-match.md, match/src/Piipan.Match.Orchestrator/Api.cs, match/src/Piipan.Match.Orchestrator/Lookup.cs, match/src/Piipan.Match.Orchestrator/Piipan.Match.Orchestrator.csproj, match/src/Piipan.Match.Orchestrator/QueryEntity.cs, match/src/Piipan.Match.Orchestrator/Startup.cs, match/src/Piipan.Match.Orchestrator/TableStorage.cs, match/src/Piipan.Match.Orchestrator/packages.lock.json, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs, match/tests/Piipan.Match.Orchestrator.Tests/packages.lock.json
Refactored approach based on conversation in #604.
- When a match is found, save the query to Table Storage and return the lookup ID.
- If there is a lookup ID collision, generate a new ID and retry insert. Repeat up to 10 times before throwing exception.
Same considerations as the previous PR:
- I've added a new Lookup class where I'm thinking the save/retrieve methods for the Lookup API can live.
- I've added a new LookupStorage class as a helper that can wrap the basic Table Storage API methods we'll be using. My intent is for it to be usable by the Lookup API (i.e., use LookupStorage.PointQueryAsync to retrieve a specific query). It should also ease dependency injection / unit testing (though see below).
- I haven't found a good way to unit test LookupStorage. The CloudTable …
=> Save match query with unique lookup ID

match/src/Piipan.Match.Orchestrator/Api.cs, match/src/Piipan.Match.Orchestrator/Lookup.cs, match/src/Piipan.Match.Orchestrator/LookupResponse.cs, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs, match/tests/Piipan.Match.Orchestrator.Tests/LookupTests.cs, match/tools/test-lookup-api.bash
- Updates orchestrator Function App with `LookupIds` entry point
- Queries table storage for a row with `RowKey` matching the incoming `lookupId`
- Returns a response containing the matching query or `null` if none
- Adds a simple bash script for manual integration testing (as a precursor to #578)
**Question**: Should the incoming lookup ID be validated according to our schema (and presumably trigger `400` responses if invalid)?
Partially addresses #259 — API will be added to APIM instance as follow on work.
---
This work can be tested locally (with a connection to the remote lookup table) using the following steps:
1. Fetch app settings for the orchestrator app (to get down binding details for the lookup table):
```
cd match/src/Piipan.Match.Orchestrator
func azure functionapp …
```
=> Add lookup API endpoint

match/src/Piipan.Match.State/Api.cs, match/tests/Piipan.Match.State.Tests/ApiTests.cs, match/tools/test-match-api.bash
- Normalize first and last to uppercase in query
- Optimize upload ID subquery
- Add manual integration test script
CSV with varying capitalization for the `Lynn,Wesley,Eura,8/01/1940,000-12-3457,` row has been uploaded to each state's participants db. The updated query can be tested using `match/tools/test-match-api.bash`.
@ryanhofdotgov I had forgotten that we already had an index on `(ssn, upload_id)`.  That is sufficient to keep the match query to an index scan, and adding an additional index on `ssn` alone seemed unnecessary.
Because of that index, normalizing with `upper()` did not have an effect on the cost:
```
-- Query without upper
Index Scan using participants_ssn_idx on participants  (cost=0.33..2.55 rows=1 width=48)
Index Cond: ((ssn = '000-12-3461'::text) AND (upload_id = …
```
=> Case insensitive matching

match/src/Piipan.Match.Orchestrator/Api.cs
Changes route from `/lookups_ids` to the correct `/lookup_ids`.
=> Fix typo in lookup_ids route

iac/arm-templates/apim.json, match/docs/duplicate-participation-api.md, match/docs/lookup.md, match/docs/orchestrator-match.md
Adds a new operation for the lookup API to the existing APIM instance. To test, send a conforming request to the API endpoint and include an active [API/subscription key](https://github.com/18F/piipan/blob/main/match/docs/duplicate-participation-api.md#calling-the-api) in the request's header. E.g.,
```
curl --location --request GET 'https://apim-duppartapi-dev.azure-api.net/v1/lookup_ids/<lookup-id>' \
--header 'Content-Type: application/json' \
--header 'Ocp-Apim-Subscription-Key: <api-key>'
```
This PR also includes some barebones documentation for the lookup API. I created #639 to take a comprehensive pass over the documentation now that most of the details have come into focus.
=> Add lookup API to APIM, update documentation

shared/src/Piipan.Shared/Authentication.cs, shared/tests/Piipan.Shared.Tests/AuthenticationTests.cs
Implements `GetAsync` method on `Shared.Authentication.AuthorizedJsonApiClient`. Necessary for making `GET` calls to internal APIs (e.g., lookup API).
Example intended usage:
```
var api = new AuthorizedJsonApiClient(httpClient, tokenProvider);
var response = await api.GetAsync(new Uri("<api-uri>/lookup_ids/AAAAAAA"));
var lookup = await response.Content.ReadAsAsync<LookupResponse>();
```
Closes #657
=> Add GetAsync method to AuthorizedJsonApiClient

iac/arm-templates/app-service-plan.json, iac/arm-templates/function-state-match.json, iac/arm-templates/function-storage.json, iac/arm-templates/participant-records.json, iac/arm-templates/virtual-network.json, iac/configure-easy-auth.bash, iac/create-resources.bash, iac/env/tts/dev.bash, iac/remove-external-network.bash, iac/secure-resources.bash
Reworking of #601, closes issues #11 and #659
Does the following:
- Shifts match api apps to core resource group (because VNets are resource-group-specific)
- Creates a single premium app service plan; puts both ETL and Match apps onto it (VNet integration is only available on premium plans or higher)
- Creates virtual network resource in separate ARM template with 2 subnets: one for the database private link, the other for the function apps
- Configures private endpoint on VNet when creating participant-records database
- Integrates ETL and Match apps with VNet
- Locks down public access to database at the end of iac by removing firewalls and changing DenyPublicAccess setting on it
Todo:
=> Set up private network for database and function apps in iac

etl/README.md, etl/docs/api.md, etl/docs/openapi/openapi.yaml, etl/docs/uploads.md
- Add state-facing instructions
- Add OpenAPI spec
- Add developer-facing documentation
Wasn't sure if the `curl` and Powershell instructions were necessary, but included them to match the format of the AzCopy instructions.
Follow-on work to #682.
=> Initial documentation for bulk upload API

docs/openapi/README.md, docs/openapi/duplicate-participation-api.yaml, docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, docs/openapi/tools/generate-docs.bash, docs/openapi/tools/generate-specs.bash, docs/quick-start-guide-states.md, match/docs/openapi/lookup/id.yaml, match/docs/openapi/lookup/index.yaml, match/docs/openapi/orchestrator/index.yaml, match/docs/openapi/orchestrator/query.yaml, match/docs/openapi/schemas/match-query.yaml
Addresses 2nd and 3rd items of #623 
- Creates a top-level OpenAPI spec to represent the Duplicate Participation API managed by APIM
- Adds a script to generate markdown documentation for this spec
- Links to this markdown documentation in State Quickstart Guide
Considerations:
- The swagger-markdown tool I originally wanted to use is incompatible with OpenApi 3.0—the generated markdown wasn't showing any info about request parameters. So I found another cli tool called [widdershins](https://github.com/Mermade/widdershins). It's normally used for generating markdown for [Slate](https://github.com/slatedocs/slate) Docs, but produces sufficient markdown on its own. Some refinement's still needed (like around the generated authentication instructions), but this was the prettiest and most …
=> create single openapi spec for apim api; generate markdown docs

match/src/Piipan.Match.State/Api.cs, match/tests/Piipan.Match.State.Tests/ApiTests.cs
Closes #708 
[Manual testing](https://github.com/18F/piipan/blob/main/match/docs/state-match.md#remote-testing) with a different first name (i.e. Teddy instead of Theodore) should return results for all states:
```
curl -X POST -i \
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${TOKEN}" \
-d '{"query": { "first": "Teddy", "last": "Farrington", "dob": "1931-10-13", "ssn": "000-12-3456" }}' \
https://ofunchaaz7alkqwuvo.azurewebsites.net/api/v1/query\?
=> remove first name from match query in state match api

iac/create-resources.bash, query-tool/src/Piipan.QueryTool/IQueryable.cs, query-tool/src/Piipan.QueryTool/Lookup.cs, query-tool/src/Piipan.QueryTool/OrchestratorApiRequest.cs, query-tool/src/Piipan.QueryTool/Pages/Index.cshtml, query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs, query-tool/src/Piipan.QueryTool/Pages/LookupById.cshtml, query-tool/src/Piipan.QueryTool/Pages/LookupById.cshtml.cs, query-tool/src/Piipan.QueryTool/Pages/Shared/_LookupResultTable.cshtml, query-tool/src/Piipan.QueryTool/Pages/Shared/_ResultsTable.cshtml, query-tool/src/Piipan.QueryTool/PiiRecord.cs, query-tool/src/Piipan.QueryTool/Startup.cs, query-tool/tests/Piipan.QueryTool.Tests/IndexTest.cs, query-tool/tests/Piipan.QueryTool.Tests/LookupByIdPageTest.cs, query-tool/tests/Piipan.QueryTool.Tests/OrchestratorApiRequestTest.cs
This PR does a few things to get the Query Tool ready to do queries based on Lookup IDs:
* Create a new page with a one-field form
* Extract the results table into a partial to share between both forms
* Adds the lookup ID field to the `PiiRecord` class
* Makes a new `Lookup` class
* Relates `Lookup` and `PiiRecord` through a `IQueryable` interface
To that last point, I opted to use an interface rather than inheritance because while both classes needed a field for the Lookup ID, it needs to be required on one but not the other, and the only ways I could think of doing that via inheritance would've required method overrides that defeated the purpose of inheritance.
Finally, while I did do a `OnPostAsync` method that returned a dummy record when you submitted the Lookup ID form, I did not …
=> Add lookup ID display and search to Query Tool

match/src/Piipan.Match.Orchestrator/Lookup.cs
Make lookup ID case-insensitive by converting it to uppercase before retrieval.
Closes #713
=> Case-insensitive lookup ID retrieval

.circleci/config.yml
Having any value for OrchApiUri will allow the home page to load when navigated to by pa11y. 
Example of a successful CI build with this config can be found [here](https://app.circleci.com/pipelines/github/18F/piipan/1020/workflows/015983ca-1972-4579-b95b-9bce825b24a1/jobs/2285).
It's worth considering as another issue whether we should start having pa11y test things like query results, which would require a useable API uri.
=> Set example env var for query tool when a11y testing in CI

.github/dependabot.yml, match/tests/Piipan.Match.State.IntegrationTests/packages.lock.json
Dependencies were updated prior to merging #744, resulting in a `error NU1004: The packages lock file is inconsistent [...]` error when running tests.
=> Update dependabot with integration tests project, fix package lock

docs/openapi/README.md, docs/openapi/bulk-api.yaml, docs/openapi/duplicate-participation-api.yaml, docs/openapi/generated/bulk-api/openapi.md, docs/openapi/generated/bulk-api/openapi.yaml, docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, docs/openapi/tools/generate-docs.bash, docs/openapi/tools/generate-specs.bash, docs/quick-start-guide-states.md, etl/docs/openapi/upload.yaml, iac/apim-bulkupload-policy.xml, iac/arm-templates/apim.json, iac/create-apim.bash
- Use state abbreviations for upload endpoints
- Dynamically generate storage account names in ARM template
- Update documentation to reflect two APIs
This starts implementing some of the API naming conventions we discussed. After this update, per-state upload endpoints will be in the following format:
```
/bulk/ea/v1/upload/filename.csv
```
This update does not change the endpoints for the `/query` or `/lookup_ids` methods.
I'm tentatively referring to the two APIs as "bulk" (or just "bulk upload" for now) and "duplicate participation" in the documentation.
The updated IaC has been run against the duppart APIM resource in `-dev` and can be viewed in the Portal.
Closes #728, related to #762.
=> Update bulk upload API naming and endpoints

etl/tools/grant-blob.bash, etl/tools/upload.bash, iac/add-front-door-to-app.bash, iac/arm-templates/database-metrics.json, iac/arm-templates/key-vault.json, iac/arm-templates/participant-records.json, iac/arm-templates/virtual-network.json, iac/configure-easy-auth.bash, iac/create-apim.bash, iac/create-databases.bash, iac/create-metrics-resources.bash, iac/create-resource-groups.bash, iac/create-resources.bash, iac/create-service-principal.bash, iac/create-state-storage-service-principal.bash, iac/delete-resources.bash, iac/env/tts/dev.bash, iac/iac-common.bash, iac/remove-external-network.bash, tools/assign-app-role.bash, tools/authorize-cli.bash
Closes #691 
- moves metrics resources into VNet resource group
- adds system type tag to identify Metrics resources
- upgrades metrics database to plan with VNet integration
- adds resources needed to integrate metrics db with VNet
- adds subnet to existing VNet for metrics database private link
- puts metrics function apps onto existing premium app service plan
- integrates metrics function apps with VNet
- locks down access to metrics db
- Also adds environment-related constants to iac-common
=> Integrate Metrics Resources in Virtual Network

iac/arm-templates/apim.json, iac/create-apim.bash
- Pass `CLOUD_NAME` env variable to ARM template
- Conditionally determine appropriate URI base
- Adapt upload hostname generation to same approach
Fixes issue when attempting to deploy APIM ARM template to Government Cloud using a `azure-api.net` hostname.
=> Dynamically generate APIM hostname

iac/apim-bulkupload-policy.xml, iac/arm-templates/apim.json
Storage resource IDs are different in Azure Commercial vs Azure Government.
Updates resource ID in per-state upload API policies so APIM can successfully retrieve managed identity authentication tokens.
Closes #769
=> Cloud-aware blob storage resource IDs in APIM

dashboard/build.bash, docs/iac.md, etl/build.bash, iac/create-resources.bash, iac/iac-common.bash, match/build.bash, metrics/build.bash, query-tool/build.bash, tools/build-common.bash
Partially addresses #529
- options to run in test-only mode or deployment mode
- deployment mode passes an Azure environment argument
=> Example of a build.bash script for dashboard subsystem

tools/update-packages.bash
`$options` was being set to a space in if no argument was passed. With the update to use double quotes to prevent globbing/splitting (#815), the space was then being passed to `dotnet restore` causing a "project not found" error.
=> Fix optional argument handling in update-packages

iac/create-metrics-resources.bash, iac/iac-common.bash, metrics/build.bash, metrics/tools/test-metricsapi.bash
Partially addresses #864 
Since Metrics names are now being used in a lot of places, I hoisted them up to iac-common. This has implications for iac scripts.
=> Start integration tests for metrics API; Make Metrics constants DRY

iac/arm-templates/event-hub-monitoring.json, iac/create-resources.bash
- Creates an Event Hub namespace following our naming conventions: `{prefix}-evh-monitoring-{env}`
- Creates an event hub resource named `logs` intended as a single location for all resource logs for a given environment
Note: Event hubs have two SKUs, "Basic" and "Standard". I've chosen Standard, which gives us certain flexibility like the ability to "capture" logs in a storage account for debugging purposes.
First step for #729, to be followed by pointing resource logs to the event hub.
=> Create Event Hub resources for streaming logs

iac/add-front-door-to-app.bash, iac/arm-templates/front-door-app-service.json
- Logs are streamed via "diagnostic settings" added via ARM template
- Added prefix and env parameters to front door ARM template so event hub resource name can be constructed
This work establishes a precedent of naming the [diagnostic setting](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings?tabs=CMD) `stream-logs-to-event-hub`. My current plan is for remaining resources which need their logs streamed to event hub to get a diagnostic setting with the same name.
=> Stream Front Door logs to Event Hub

iac/create-resources.bash
fixes piipan and subsystem tags from being merged on etl function apps.
=> fix: function app tag typo

ddl/per-state.sql, etl/docs/csv/example.csv, etl/docs/csv/import-schema.json, etl/src/Piipan.Etl/BulkUpload.cs, etl/src/Piipan.Etl/PiiRecord.cs, etl/src/Piipan.Etl/PiiRecordMap.cs, etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs
Closes #860 
Since this changes the database schema, I'll drop participants database server and re-run iac on tts/dev before merging this. 
Per [this discussion](https://github.com/18F/piipan/issues/860), I made the following choices:
- Database column name and C# object property are named `benefits_end_date` since it's technically a postgresql `date` column and a `DateTime` C# object. 
- However in the bulk upload csv, the field is named "benefits end month" since we're assuming the month is all states will be tracking. The import schema has a data type of [yearmonth](https://specs.frictionlessdata.io/table-schema/#types-and-formats) that seemed most appropriate. 
- Our system takes on the responsibility of determining the final day of benefits based on the provided month. I'm not sure …
=> Add benefits end date to participants database and bulk upload

docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, iac/arm-templates/function-state-match.json, iac/create-resources.bash, match/docs/openapi/schemas/pii-record.yaml, match/src/Piipan.Match.Orchestrator/MatchResponse.cs, match/src/Piipan.Match.State/MatchResponse.cs, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs, match/tests/Piipan.Match.State.IntegrationTests/ApiIntegrationTests.cs, match/tests/Piipan.Match.State.Tests/ApiModelTests.cs, match/tests/Piipan.Match.State.Tests/ApiTests.cs, match/tests/docker-compose.yml
- Removes `state_name` entirely from state match, orch match, openapi docs, and IaC
- Renames `state_abbr` to `state`, preserving `state_abbr` as a deprecated property
Closes #895.
=> Remove `state_name` from DupPart API

query-tool/src/Piipan.QueryTool/Pages/Shared/_ResultsTable.cshtml, query-tool/src/Piipan.QueryTool/PiiRecord.cs, query-tool/tests/Piipan.QueryTool.Tests/IndexTest.cs, query-tool/tests/Piipan.QueryTool.Tests/OrchestratorApiRequestTest.cs
- Remove state_name field from models and templates
- Use state field in templates
- Update tests
Follow on work from #954.
Closes #953.
=> Update Query Tool to use new state API field

docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, match/docs/openapi/lookup/id.yaml, match/docs/openapi/orchestrator/query.yaml, match/docs/openapi/schemas/lookup.yaml, match/docs/openapi/schemas/match-query.yaml, match/docs/openapi/schemas/pii-record.yaml
- Regenerated documentation
- Tried to keep examples as close as possible to their associated models to minimize the chance they fall out of date
- Widdershins does not currently support multiple request examples for markdown, only displays first example
The primary change here is adding examples to the API documentation used by states: https://github.com/18F/piipan/blob/413b021c906658a44732348e1a358a1bc457ff71/docs/openapi/generated/duplicate-participation-api/openapi.md
Closes #899, but will need to be kept up to date with scheduled API updates (included #911).
=> Add example requests and responses for DupPart API

iac/arm-templates/database-metrics.json, iac/arm-templates/participant-records.json, iac/create-metrics-resources.bash, iac/create-resources.bash
- Participant records DB
- Metrics "core" DB
- Only streams `PostgreSQLLogs` logs, does not include performance-related `QueryStoreRuntimeStatistics` or `QueryStoreWaitStatistics` logs
Partially addresses #969
=> Stream PSQL logs to event hub

docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, match/docs/openapi/schemas/pii-record.yaml
With #898 complete, adds new `benefits_end_month` field to examples.
=> Add benefits_end_month to openapi examples

dashboard/build.bash, query-tool/build.bash
Closes #949.
This avoids problem where solution file publishes both src and test trees resulting in a failed deploy. It doesn't solve the problem exactly as #949 suggests, but it should get the job done and is similar to how the deploy is written for our function apps.
=> Change working dir to app tree before publishing

iac/arm-templates/blob-storage.json, iac/arm-templates/event-hub-monitoring.json, iac/create-resources.bash
- Event Hub API version 2021-01-01-preview not supported in AzureUSGoverment:
https://portal.azure.us/#blade/HubsExtension/ArmExplorerBlade
- Azure Monitor is not supported for Azure Blob Storage in AzureUSGovernment, reverts #950:
https://docs.microsoft.com/en-us/azure/storage/blobs/monitor-blob-storage?tabs=azure-portal
=> Revert monitoring to accommodate AzureUSGoverment

iac/env/tts/test.bash
This change keeps tts/test in sync with tts/dev
=> Deprecate metrics resource group in tts/test

ddl/per-state.sql, etl/docs/csv/example.csv, etl/docs/csv/import-schema.json, etl/src/Piipan.Etl/BulkUpload.cs, etl/src/Piipan.Etl/PiiRecord.cs, etl/src/Piipan.Etl/PiiRecordMap.cs, etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs
Closes #850 
- I was unable to get a mishandled Boolean field to throw a Validation Exception. They seem to be caught at the conversion level. After some googling, I [found](https://stackoverflow.com/a/22998705) that a custom validator may be the only way to catch validation errors with booleans. A custom validator didn't seem necessary at this time, since acceptable values for true and false are provided [in other ways](https://joshclose.github.io/CsvHelper/examples/configuration/attributes/). 
- Adds optional `protect_location` boolean field to Bulk Upload API 
- Adds `protect_location` column to example upload csv
- Since database schema is changed, I'll merge once iac has been run on tts/dev for these changes.
=> Add protect_location field to bulk upload import

etl/src/Piipan.Etl/PiiRecordMap.cs, etl/tests/Piipan.Etl.Tests/BulkUploadTests.cs
This permits the CSV header to be omitted from CSV file for optional fields, which will be important for preserving backwards compatibility.
Consistency should be maintained between optional fields in import-schema.json, which C# members are marked as nullable, and what maps are Optional.
*Note*: we want validate.py to still look for – and fail – if all of our currently defined columns are not present, as we want devs to move towards all the current columns. May have to revisit once the API has reached "1.0" status and support validation of previous versions.
- For backwards compatibility, columns, not just field values, are optional when CSV schema does not list them as required. validator.py will still fail if all defined columns are not present.
=> Specify CSV fields that are optional

etl/docs/csv/import-schema.json
Should generally match query response API description
=> Wordsmithing protect location field description

docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, etl/docs/csv/import-schema.json, match/docs/openapi/schemas/pii-record.yaml, match/src/Piipan.Match.Orchestrator/MatchResponse.cs, match/src/Piipan.Match.State/Api.cs, match/src/Piipan.Match.State/MatchResponse.cs, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs, match/tests/Piipan.Match.State.IntegrationTests/ApiIntegrationTests.cs, match/tests/Piipan.Match.State.IntegrationTests/DbFixture.cs, match/tests/Piipan.Match.State.Tests/ApiModelTests.cs, match/tests/Piipan.Match.State.Tests/ApiTests.cs
Closes #989 
- Adds protect_location field to matches in Duplicate Participation query responses
=> Add protect_location to match query api response

match/src/Piipan.Match.Orchestrator/Api.cs, match/src/Piipan.Match.State/Api.cs, metrics/src/Piipan.Metrics/Piipan.Metrics.Api/GetParticipantUploads.cs
Covers all HTTP triggered Functions with EasyAuth enabled:
- State query call
- Orchestrator query call
- Orchestrator lookup_ids call
The log message displays as `Executing request from user (null)` in a couple contexts:
- If `HttpRequest.HttpContext.User` is not set, as is the case in local development where the Function does not sit behind EasyAuth
- If `HttpRequest` does not contain an `HttpContext` object, as is the case when running tests with a mocked `HttpRequest`
Partially addresses #970.
=> Log managed identity when executing match API requests

query-tool/src/Piipan.QueryTool/Pages/Shared/_ResultsTable.cshtml, query-tool/src/Piipan.QueryTool/PiiRecord.cs
Closes #869 
Closes #851 
- null `protect_location` values will show up as "Yes"; true as "Yes"; false as "No"
- No `recent_benefit_months` is shown as an empty column
@cjhskippy @erinzstrenio See image below. Thoughts on wording for these new columns?
Also, the results table is getting pretty scrunched. A common way to handle that is by giving the table a fixed width and making it horizontally scrollable. This results in some of the trailing data being hidden unless the user scrolls. I'd welcome any ideas on the design of that, or we can hold off until Julia gets back.
=> Add recent benefit months and protect location to query tool results

iac/configure-easy-auth.bash
Doc referenced create-resources rather than configure-easy-auth, presumably a copy-and-paste issue.
=> Update configure-easy-auth doc with correct script name

iac/arm-templates/dashboard-app.json, iac/arm-templates/query-tool-app.json
Removing the ipSecurityRestrictions property in ARM template does not clear any existing firewall rules, but leaves it unchanged. Need to explicitly set the property to an empty array.
Firewall rules can be cleared since Easy Auth is enabled since 622b1a9b17b2fb63abf366f282130ed97587b91d
=> Clear app firewall rules for dashboard and query tool

iac/arm-templates/dashboard-app.json, iac/configure-easy-auth.bash
- Add new `Metrics.Read` app role
- Configure Dashboard with a system-assigned identity
- Turn on authentication for metrics API
Partially address #1055. Breaks dashboard's ability to access metrics API until a follow up PR that will add in authenticated requests.
=> Configure Easy Auth between dashboard and metrics API

dashboard/docs/dashboard.md, dashboard/src/Piipan.Dashboard/Api/ParticipantUploadRequest.cs, dashboard/src/Piipan.Dashboard/Piipan.Dashboard.csproj, dashboard/src/Piipan.Dashboard/Startup.cs, dashboard/src/Piipan.Dashboard/packages.lock.json, dashboard/tests/Piipan.Dashboard.Tests/Api/ParticipantUploadRequestTests.cs, dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
- Inject shared `AuthorizedJsonApiClient` instead of `HttpClient`
- Adapt `ParticipantUploadRequest` to work with `AuthorizedJsonApiClient`
- Update tests and doc
Partially addresses #1055.
I have a follow up issue to refine the documentation around local testing (#1091).
=> Make authenticated requests when calling metrics API from dashboard

dashboard/docs/dashboard.md, docs/securing-internal-apis.md, match/docs/orchestrator-match.md, match/docs/state-match.md, query-tool/docs/query-tool.md, tools/assign-app-role.bash, tools/authorize-cli.bash
- Bring tool parameters into sync
- Centralize docs, link out in sub-system docs
Closes #1091.
Follow up from #1092.
=> Refine docs and tools for calling secured APIs locally

iac/arm-templates/dashboard-app.json, iac/arm-templates/query-tool-app.json, iac/iac-common.bash
Closes #1042. App Service instances under Linux to not have as many logging options and do not have the networking UI in the portal that makes it easy to understand the networking config.
Updated IaC has been run on tts/dev.
Deploy notes:
- manually drop existing app service instances as cannot update in place due to platform change/service plan change
- rerun IaC
- manually drop obsolete Linux service plan `piipan-app-plan`
=> Change App Service instances to Windows

iac/create-core-databases.bash
- Pull common procedures out to functions
- Bring roles and privileges closer to how they are handled in `participant-records`, though maintains use of `public` schema
- Create managed roles for Metrics API (read) and Metrics Collect (read/write)
Partially addresses #409. Would definitely appreciate a keen eye on the roles and privileges.
Subsequent updates will switch applications to use managed identities when connecting to database and remove vestigial Key Vault references.
=> Configure core database with managed roles

iac/create-core-databases.bash
I missed this with #1100 — the read/write role was granted privileges for tables but not sequences, resulting in errors like:
```
[Error] 42501: permission denied for sequence participant_uploads_id_seq
```
=> Give read/write role privileges for sequences

iac/create-metrics-resources.bash, metrics/src/Piipan.Metrics/Piipan.Metrics.Api/GetParticipantUploads.cs, metrics/src/Piipan.Metrics/Piipan.Metrics.Api/Piipan.Metrics.Api.csproj, metrics/src/Piipan.Metrics/Piipan.Metrics.Api/packages.lock.json, metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/BulkUploadMetrics.cs, metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/Piipan.Metrics.Collect.csproj, metrics/src/Piipan.Metrics/Piipan.Metrics.Collect/packages.lock.json, metrics/tests/Piipan.Metrics.Tests/packages.lock.json
- Update connection strings, switching user to system-assigned identity
- Remove unnecessary Key Vault configuration
- Move system-assigned identity creation to initial function creation command
- Update application code to use managed identity and shared authentication library when building database connection string
Closes #409.
IaC has been run against `tts/dev`.
Deploy notes:
- Manually delete unused `kv-metrics` Key Vault
- Manually revoke permissions in `kv-core` for each Function app:
```
principalId=$(az functionapp identity show \
-g "RESOURCE_GROUP" \
-n "$METRICS_COLLECT_APP_NAME" \
--query principalId \
-o tsv)
az keyvault delete-policy \
-n "$VAULT_NAME" \
--object-id "$principalId"
```
=> Use managed identity when metrics functions connect to database

docs/iac.md, iac/create-metrics-resources.bash
- Conditionally add access restriction for `AzureEventGrid` service tag
- Requires AZ CLI >= 2.23, earlier versions [throw error](https://github.com/Azure/azure-cli/issues/16661#issuecomment-839551317) when using `--service-tag` parameter (could also be resolved by switching to an ARM template)
Closes #1055. Implementing managed identities has been adding to the backlog as #1111.
=> Restrict Metrics Collector to Event Grid at network level

iac/arm-templates/dashboard-app.json, iac/arm-templates/query-tool-app.json
Pull in the email and profile OIDC scopes by default for our App Service instances.
=> Add email and profile OIDC scopes

iac/create-core-databases.bash
Fixes IaC bug in `create-core-databases`.
If creating a new database, passing the incoming database name to psql as the `-d` parameter will throw an error. Instead, pass `TEMPLATE_DB`.
Precursor to #701.
=> Pass template database to psql when creating new database

iac/create-core-databases.bash
Prep work to better support creating multiple databases within `create-core-databases.bash`.
Precursor to #701.
=> Namespace `DB_NAME` and inline `DB_TABLE_NAME`

docs/adr/0015-do-not-use-table-storage.md
Provides context around our decision to avoid Table storage moving forward, our preference for PostgreSQL, and evaluation criteria if deviating from our preference.
Partially addresses #701.
=> ADR on using Azure Table storage as NoSQL datastore

docs/iac.md, iac/configure-oidc.bash, iac/create-metrics-resources.bash, iac/create-resources.bash
Closes #1039 
Adds `configure-oidc.bash`, which, given an environment and application name, sets the `IDP_CLIENT_SECRET` after pulling the current value from the appropriate vault. This approach assumes the existence of a Key Vault which contains an OIDC secret, both following standard naming conventions. 
`configure-oidc.bash` is run as part of IaC for the Dashboard and Query Tool applications, but can be run as a one-off to accommodate updated client secrets.
=> Automate configuration of IDP client secrets

iac/create-metrics-resources.bash, iac/create-resource-groups.bash, iac/create-service-principal.bash, iac/delete-resources.bash, iac/env/tts/dev.bash, iac/env/tts/test.bash, metrics/tools/test-metricsapi.bash
Closes #1025 
Removes all references to `METRICS_RESOURCE_GROUP` and replaces them with `RESOURCE_GROUP`.
=> Remove METRICS_RESOURCE_GROUP from IaC scripts

etl/docs/csv/import-schema.json
Recent benefit months do not need to be consecutive. 
For example, if current month is July and an individual received benefits in March, April, and June (but not May), data can be `2021-03 2021-04 2021-06`
Relaxing bulk upload rule for `recent_benefit_months` requiring months needing to be consecutive. Recent Benefit Months no longer need to be consecutive.
=> Change rule for consecutive recent benefit months in import schema

iac/configure-cis-policy.bash, iac/create-resources.bash
Closes #828 
Adds `configure-cis-policy.bash`, which assigns the CIS Microsoft Azure Foundations Benchmark to both the core and match resource groups.
=> Configure CIS Azure Benchmark policy as part of IaC

iac/arm-templates/function-orch-match.json, iac/create-resources.bash
- Update orchestrator ARM template to use existing premium plan
- Add function app to vnet
Updated IaC has been run against `tts/dev`.
Closes #694
The orchestrator function app can't be updated in place because it is being assigned to a higher-level app service plan. It must be deleted before running the updated IaC on new environments:
```
az resource delete \
-g "$MATCH_RESOURCE_GROUP" \
-n "$ORCHESTRATOR_FUNC_APP_NAME" \
--resource-type "Microsoft.Web/sites"
az resource delete \
-g "$MATCH_RESOURCE_GROUP" \
-n "$ORCHESTRATOR_FUNC_APP_NAME" \
--resource-type "Microsoft.Insights/components"
```
=> Move orchestrator function to core vnet

iac/configure-defender.bash, iac/create-resources.bash
Closes #392 
Adds `configure-defender.bash`, which enables Azure Defender at the `standard` tier for all storage accounts at the subscription level.
=> Enable Azure Defender for storage accounts

iac/apim-duppart-policy.xml
- Forwards value as an HTTP header that follows the `Ocp-Apim-Subscription-` naming pattern Azure uses for API keys
- Implements forwarding logic via the APIM policy
Closes #683.
I created a follow-on ticket for logging this information: #1170.
=> Forward APIM subscription key name to Orchestrator

metrics/README.md
Closes #952 
- Verified that no undocumented steps are necessary to run the dashboard locally
- Added a `Local development` section to the Metrics README, which documents the same limitations to local development that are mentioned for the per-state APIs.
=> Update local development instructions

docs/adr/0015-use-json-api-spec-for-apis.md, docs/adr/0016-use-json-api-spec-for-apis.md
A discussion came up while doing #1082 about possibly standardizing our response schemas across our API's. Here's an initial proposal to use a subset of the JSON API schema for this purpose.
=> Add ADR for JSON API proposal

iac/arm-templates/activity-log.json, iac/create-resources.bash
Adds a diagnostic setting to the subscription's Activity Log which sends `Policy` logs to [event hub](https://github.com/18F/piipan/blob/dev/docs/log-streaming.md).
Closes #1093. See that issue for more details on log messages.
=> Stream Policy operations from Activity Log to event hub

iac/apim-policy.xml, iac/arm-templates/apim.json, iac/create-apim.bash
Closes #684 
Adds `apim-policy.xml` prevents the usage of the automatically generated all-access APIM subscription keys. Attempts to use these keys for API calls results in the same `401` response that would be returned with an invalid subscription key.
Updates IaC to apply `apim-policy.xml` to the APIM globally.
=> Disallow usage of all-access APIM keys

docs/openapi/duplicate-participation-api.yaml, docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, match/docs/openapi/lookup/id.yaml, match/docs/openapi/orchestrator/query.yaml, match/docs/openapi/schemas/lookup.yaml, match/docs/openapi/schemas/match-query.yaml, match/docs/openapi/schemas/pii-record.yaml
Satisfies schema/documentation changes only for #368 
I found it easiest to review the changes by viewing the `docs/openapi/generated/duplicate-participation-api/openapi.md` file for this branch. 
Summarizing the different areas we talked about:
Switching to a Bulk API means:
1. we need both item-level and top-level error handling
1. we need to properly relate people requested to their results
1. metadata may become more important 
1. parameter and property names will change
All these things pushed us to think about standardizing our response schemas across our APIs. We're considering [JSON API](https://github.com/18F/piipan/pull/1119) for this purpose. 
See the schema for how top-level and item-level errors are handled. 
For item-level errors, we're using Amazon's Bulk API approach to …
=> Change match query API schema to accept and return arrays

iac/arm-templates/function-orch-match.json, iac/arm-templates/function-state-match.json
Enables `alwaysOn` configuration property to avoid cold starts when calling the duplicate participation API.
Closes #1163.
=> Enable always on setting for match function apps

query-tool/src/Piipan.QueryTool/OrchestratorApiRequest.cs, query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs, query-tool/src/Piipan.QueryTool/Pages/Shared/_ResultsTable.cshtml, query-tool/src/Piipan.QueryTool/PiiRecord.cs, query-tool/tests/Piipan.QueryTool.Tests/IndexTest.cs, query-tool/tests/Piipan.QueryTool.Tests/OrchestratorApiRequestTest.cs
Closes #1121 
Relies on #1098
This is a quick fix to ensure there are no breaking changes from the API switch to households.
No new UI was added.
Validation and other data-level errors aren't being shown in the UI.
=> Update query tool to handle household match requests/responses

iac/arm-templates/dashboard-app.json, iac/arm-templates/front-door-app-service.json, iac/arm-templates/query-tool-app.json
- Add an empty, static HTML file to each app
- Add static file to excludedPaths in ARM template auth settings
- Point Front Door to excluded path
Depending on the outcome of #1125, this approach can be easily adapted by pointing to a new path and removing the static HTML file.
Closes #1131.
=> Add authentication exception for health probes

docs/create-ad-b2c-idp.md
Relates to #1126 and #1127 
Updates Azure B2C documentation to include a newly required step after creating a new application user.
=> Update b2c docs to include profile editing step

match/src/Piipan.Match.Orchestrator/Api.cs
- Log the custom subscription name header established in #1171 
- Remove nullable reference type (and directive) to clear up compiler warnings
If/when we make the move to .NET 5/6 we should be able to clean up all this logging using either some custom [middleware](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#middleware) or perhaps something similar to the [ASP.NET `AddHttpLogging` method](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0#http-logging-options) (if it exists for Function apps).
Closes #1170
=> Log APIM subscription name in Orchestrator

query-tool/src/Piipan.QueryTool/Startup.cs, query-tool/src/Piipan.QueryTool/appsettings.Development.json, query-tool/src/Piipan.QueryTool/appsettings.json, query-tool/src/Piipan.QueryTool/appsettings.tts.json, query-tool/src/Piipan.QueryTool/mock_user.json
Closes #1129
Adds a default authorization policy to the Dashboard that requires the user to have particular claims in order to access the application. The required claims are configurable via appsettings. If no authorization policy is configured in appsettings, all requests are rejected with 403 - Forbidden.
Reuses much of #1128 via `Piipan.Shared`
=> Add OIDC claim-based authorization policy to Query Tool

docs/create-ad-b2c-idp.md
Closes #1336
Updates the Azure B2C IDP documentation to include instructions for creating new user attribute types (claim types) as well as updating attributes for specific users (claim values).
=> Update B2C docs for creating, updating user claims

iac/arm-templates/dashboard-app.json, iac/arm-templates/query-tool-app.json
Normally we would not explicitly disable a feature that was already turned off by default, but as it was very useful for debugging OIDC claim issues, it seems appropriate to leave a "bread crumb".
[Enabling the token store enables the /.auth/me URL that prints the current user's OIDC claims.](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities#access-user-claims-using-the-api)
=> Explicitly disable token store and document

iac/arm-templates/dashboard-app.json, iac/create-metrics-resources.bash
Partially addresses #1029; similar to work done for query tool in #1380
The sign-out link however is now broken; wants to redirect to App Service URL for ../complete rather than the Front Door URL. Will address in separate PR.
**Deploy notes**
- Updated B2C app registration to allow Front Door callback URL, deleted App Service callback URL
=> Configure Easy Auth and Front Door for dashboard

iac/arm-templates/query-tool-app.json, iac/create-resources.bash
Partially addresses #1029; similar config will be done on dashboard in follow-on PR.
The sign-out link however is now broken; wants to redirect to App Service URL for ../complete rather than the Front Door URL. Will address in separate PR.
**Deploy notes**
- Updated B2C app registration to allow Front Door callback URL, deleted App Service callback URL
=> Configure Easy Auth and Front Door for query tool

ddl/apply-ddl.bash, ddl/per-state.sql, iac/create-databases.bash
- Create `NOLOGIN` role with permission to connect to each state database
- Grant role `SELECT` permission to necessary tables
Intent is for this role to be granted to the forthcoming orchestrator managed identity role (and potentially a future bulk match identity role).
Creating this role/group may be overkill if it's used by only one or two identities, but this approach is intended to avoid making `create-databases.bash` dependent on other resources.
Partially addresses #1339.
=> Add read-only role to participants DB cluster

iac/arm-templates/front-door-app-service.json
Now that Easy Auth is enabled at App Service Level, we can drop the Front Door firewall rules that restricted access to the GSA network.
=> With Easy Auth at web app, drop FD firewall rules

dashboard/src/Piipan.Dashboard/Pages/BasePageModel.cs, dashboard/src/Piipan.Dashboard/Pages/Index.cshtml.cs, dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml.cs, dashboard/src/Piipan.Dashboard/Pages/Shared/_Layout.cshtml, dashboard/src/Piipan.Dashboard/Startup.cs, dashboard/tests/Piipan.Dashboard.Tests/IndexPageTest.cs, dashboard/tests/Piipan.Dashboard.Tests/ParticipantUploadsModelTests.cs, query-tool/src/Piipan.QueryTool/Pages/BasePageModel.cs, query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs, query-tool/src/Piipan.QueryTool/Pages/Shared/_Layout.cshtml, query-tool/src/Piipan.QueryTool/Startup.cs, query-tool/tests/Piipan.QueryTool.Tests/IndexTest.cs
Closes #1383 
- Configures [forwarded headers middleware](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1) so that the `post_logout_redirect_uri` points back to Azure FD rather than the App Service. 
- Pulls properties that are references in shared Razor pages (e.g. `_Layout.cshtml`) up into `BasePageModel` rather than having them duplicated across `PageModels`
=> Make sign out links work with Azure Front Door

iac/config-managed-role.bash, iac/create-resources.bash
The bulk of the diff for `iac/create-resources.bash` is from re-ordering existing code so the current CLI user remains a member of the Azure AD admin group until after the orchestrator's role is added to the `participant-records`.
I'm [still deferring](https://github.com/18F/piipan/pull/1100#discussion_r658080454) unifying our db commands into a set of common utilities — until then `iac/config-managed-role.bash` duplicates some code. Happy to address this now if others think it's the right time.
Partially addresses #1339
=> Add database role for orchestrator identity

docs/openapi/duplicate-participation-api.yaml, docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, match/docs/openapi/orchestrator/find-pii.yaml, match/docs/openapi/orchestrator/find.yaml, match/docs/openapi/orchestrator/index.yaml, match/docs/openapi/schemas/match-query.yaml, match/docs/openapi/schemas/participant-record.yaml
- Update both internal-facing and state-facing specs, keeping internal-facing PII-based endpoint
- Bump all endpoints from `v1` to `v2`
- Rename endpoints from `/query` to `/find_participants`
- Remove PII fields (name, dob, ssn) from response
As usual, it may be easiest to review the state-facing changes by looking at `docs/openapi/generated/duplicate-participation-api/openapi.md`. Internal-facing changes might be easiest to review by pulling down this branch, running `match/tools/generate-specs.bash` and reviewing at the output in `match/docs/openapi/orchestrator/generated`.
@cjhskippy @ryanhofdotgov Should the internal-facing PII endpoint still require match requests include first name?
@ryanhofdotgov @echappen @timoballard tagging all of you since I'm using this change as an …
=> Update API specs to incorporate PPRL approach

match/tests/Piipan.Match.Orchestrator.IntegrationTests/Piipan.Match.Orchestrator.IntegrationTests.csproj
(Dependabot caught this once `dependabot.yaml` was updated).
=> Bump coverlet.collector to 3.1.0

match/src/Piipan.Match.Orchestrator/Api.cs, match/src/Piipan.Match.Orchestrator/OrchMatchRequest.cs, match/src/Piipan.Match.Orchestrator/OrchMatchRequestValidator.cs, match/src/Piipan.Match.Orchestrator/OrchMatchResponse.cs, match/src/Piipan.Match.Orchestrator/ParticipantRecord.cs, match/tests/Piipan.Match.Orchestrator.IntegrationTests/ApiIntegrationTests.cs, match/tests/Piipan.Match.Orchestrator.IntegrationTests/DbFixture.cs, match/tests/Piipan.Match.Orchestrator.IntegrationTests/Piipan.Match.Orchestrator.IntegrationTests.csproj, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs, match/tests/Piipan.Match.Orchestrator.Tests/OrchMatchRequestValidatorTests.cs, match/tools/test-match-api.bash
- Replace PII properties with hash property
- Update SQL query/matching algorithm
- Align integration tests database fixture with recent work in `Piipan.Etl`
- Use Dapper in database fixture
Partially addresses #1215.
Note: the PII-based endpoint `/find_matches_by_pii` is stubbed in and currently returns just a 204 response.
=> Update match API to use de-identified data

docs/openapi/duplicate-participation-api.yaml, docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, iac/arm-templates/apim.json
- Use "match" as a name space for the duplicate participation API
- Update APIM policy to use new endpoint and remove extraneous properties (description, responses)
Another naming decision.
Closes #1510 and #1215.
=> Add name spaced find_matches endpoint to APIM

docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, match/docs/openapi/schemas/participant-record.yaml, match/src/Piipan.Match.Orchestrator/ParticipantRecord.cs, match/tests/Piipan.Match.Orchestrator.Tests/ApiTests.cs
With the recent API churn, it seems like it's time to drop the deprecated property completely. 
Closes #1550
=> Drop state_abbr property from DupPart API

dashboard/src/Piipan.Dashboard/ParticipantUpload.cs, dashboard/src/Piipan.Dashboard/Piipan.Dashboard.csproj, dashboard/src/Piipan.Dashboard/packages.lock.json, dashboard/tests/Piipan.Dashboard.Tests/Api/ParticipantUploadTests.cs, dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json
- Update application
- Add tests for `ParticipantUpload` methods
Closes #1562. Fixes issue where Dashboard would not display any participant upload results.
Note: [Requires runtime environment has access to timezone data](https://github.com/mattjohnsonpint/TimeZoneConverter#note-on-os-data-dependencies).
=> Use TimeZoneConverter for retrieving TimeZoneInfo objects

iac/create-core-databases.bash, iac/db-common.bash, iac/iac-common.bash, metrics/ddl/metrics.sql
Moves database-related functionality out of `create-core-databases.bash` and into a share common script. Namespaces/prefixes all functions with `db_`.
Prep work for creating the match records database required by #1546.
Closes #1493, incidentally.
There's some follow on work to update `create-databases.bash` to use the common functionality where possible.
=> Refactor IaC database tools to common script

match/ddl/match-record.sql
Partially address #1546 — starting with the database schema before getting into implementation.
Trying to keep this as simple as possible for meeting the needs of the ticket, knowing that requirements are still coming into focus and the underlying implementation is likely to change.
=> Initial database schema for match records

iac/create-core-databases.bash, iac/db-common.bash, match/ddl/match-record.sql
- Update `db_create_managed_role` to allow other resource groups when creating managed identities
- Make DDL re-runnable by handling case where ENUMs already exist
- Fix typo in schema
Partially addresses #1546
=> Create match records database in IaC

etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/Startup.cs, etl/tests/Piipan.Etl.Func.BulkUpload.IntegrationTests/BulkUploadIntegrationTests.cs, etl/tests/Piipan.Etl.Func.BulkUpload.Tests/StartupTests.cs, match/src/Piipan.Match/Piipan.Match.Core/DataAccessObjects/CollaborationDb.cs, match/src/Piipan.Match/Piipan.Match.Core/DataAccessObjects/MatchRecordDao.cs, match/src/Piipan.Match/Piipan.Match.Func.Api/Startup.cs, match/tests/Piipan.Match.Core.IntegrationTests/MatchRecordDaoTests.cs, match/tests/Piipan.Match.Func.Api.IntegrationTests/ApiIntegrationTests.cs, match/tests/Piipan.Match.Func.Api.Tests/StartupTests.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/ParticipantDao.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/ParticipantDb.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/UploadDao.cs, participants/tests/Piipan.Participants.Core.IntegrationTests/ParticipantDaoTests.cs, participants/tests/Piipan.Participants.Core.IntegrationTests/UploadDaoTests.cs, participants/tests/Piipan.Participants.Core.Tests/Extensions/ServiceCollectionExtensionsTests.cs, shared/src/Piipan.Shared/Database/AzurePgConnectionFactory.cs, shared/src/Piipan.Shared/Database/BasicPgConnectionFactory.cs, shared/src/Piipan.Shared/Database/IDbConnectionFactory.cs, shared/tests/Piipan.Shared.Tests/Database/AzurePgConnectionFactoryTests.cs, shared/tests/Piipan.Shared.Tests/Database/BasicPgConnectionFactoryTests.cs
- Adds DAO-specific placeholder types (e.g., `struct ParticipantsDb`)
- Updates implementations and tests across all subsystems
Note: OmniSharp caught some whitespace and import ordering. Toggling off whitespace changes might make review a little simpler.
Closes #1795
=> Make IDbConnectionFactory generic and update implementations

CHANGELOG.md
Release has [already been cut](https://github.com/18F/piipan/releases/tag/v0.92). Merging the release branch back to dev to include CHANGELOG update.
=> Release v0.92 back to dev

docs/roadmap.md
Likely makes sense to prioritize disposition reporting earlier so that usability testing for that process can take place.
=> Draft revisions to roadmap

docs/iac.md, iac/arm-templates/function-orch-match.json, iac/arm-templates/virtual-network.json, iac/create-metrics-resources.bash, iac/create-resources.bash, iac/iac-common.bash
- Adds NSG to virtual network with necessary outbound rules for allowing deployment and execution
- Associates NSG with subnet used by function apps
- Enables setting on function apps to route all traffic through vnet
- Updates IaC docs to reflect new Azure CLI version requirement (setting `vnet-route-all-enabled` via the CLI is only possible with versions >=2.27.0 and only versions >=2.30.0 fix the previous issue with AAD administration for our PostgreSQL clusters)
Closes #1164
=> Limit network egress for function apps

iac/arm-templates/dashboard-app.json, iac/arm-templates/query-tool-app.json, iac/arm-templates/virtual-network.json, iac/create-metrics-resources.bash, iac/create-resources.bash, iac/iac-common.bash
- Add new subnet for app service apps
- Add network security group for app subnet that limits outbound traffic to only AAD and App Service
- Enable vnet integration for both web apps
- Enable setting to route all outbound web app traffic to vnet
Same approach as #2261, but locked down a little more by not allowing traffic to storage accounts.
Closes #1165 
Closes #1166
=> Limit egress traffic for dashboard and query tool

CHANGELOG.md
Release has [already been cut](https://github.com/18F/piipan/releases/tag/v0.93). Merging the release branch back to dev to include CHANGELOG update.
=> Release v0.93 back to `dev`

iac/arm-templates/function-orch-match.json, iac/create-resources.bash
Closes #2324 
Related to #2258 
Configures the orchestrator function app storage account to disallow default network access. Access is granted only to `vnet-core-$ENV/snet-apps1-$ENV`.
This case is slightly different from the other storage accounts, in that this account is part of the `rg-match` resource group, as opposed to `rg-core`. This seems to cause issues when attempting to publish the function app while network access restrictions are in place. To get around these issues, we temporarily disable the network firewall while executing the function app publish step.
=> Deny default access to Orchestrator function storage account

docs/securing-internal-apis.md, iac/arm-templates/dashboard-app.json, iac/arm-templates/query-tool-app.json, iac/configure-easy-auth.bash, iac/create-apim.bash, iac/create-metrics-resources.bash, iac/create-resources.bash, match/src/Piipan.Match/Piipan.Match.Client/Extensions/ServiceCollectionExtensions.cs, match/tools/test-orch-match-api.bash, metrics/src/Piipan.Metrics/Piipan.Metrics.Client/Extensions/ServiceCollectionExtensions.cs, metrics/tools/test-metricsapi.bash
After this update, clients of our internal APIs secured with app service authentication must request an access token from the API using the URI `api://<aad-app-id>`, consistent with [Microsoft's new guidance](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains). Before, clients requested a token from the hostname of the API, e.g. `https://<app-name>.azurewebsites.net`.
- Change sequencing of AAD app registration so it is available for subsequent configuration later in the IaC process.
- Update easy auth config to use new `api://<app-id>` format
- Remove unnecessary easy auth config settings
- Update APIM to use new URI format in DupPart policy
- Add new …
=> Update approach to App ID URI usage for App Service Authentication

iac/create-resources.bash
Fixes a bug introduced in #2352 
Now that the key vault relies on event hub monitoring, event hub monitoring should be created before the key vault.
=> Fix: switch creation order for key vault and event hub monitoring

iac/arm-templates/function-orch-match.json, iac/create-resources.bash
Apply networking restrictions after base function app and backing storage account are deployed.
Loosely follows Microsoft's [guide for restricting traffic to a function app's storage account](https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network). (But does not create multiple storage accounts and lets ARM handle file share creation/configuration).
This brings the ordering of the orchestrator deployment closer to [that of our ETL apps](https://github.com/18F/piipan/blob/dev/iac/create-resources.bash#L393-L430). One key difference remains: the ETL apps are able to deploy the storage account with the [`networkAcls` in place](https://github.com/18F/piipan/blob/dev/iac/arm-templates/function-storage.json#L37-L45). …
=> Re-sequence orchestrator networking config in IaC

iac/iac-common.bash
Closes #2495 
Prior to this change and after #2463, applications using PostgreSQL database connection strings with `Ssl Mode=Required` would throw:
```
NpgsqlException
To validate server certificates, please use VerifyFull or VerifyCA instead of Require. To disable validation, explicitly set 'Trust Server Certificate' to true. See https://www.npgsql.org/doc/release-notes/6.0.html for more details.
```
=> Use VerifyFull SSL mode in PostgreSQL connection strings

etl/tests/Piipan.Etl.Func.BulkUpload.IntegrationTests/BulkUploadIntegrationTests.cs, match/src/Piipan.Match/Piipan.Match.Core/DataAccessObjects/MatchRecordDao.cs, metrics/src/Piipan.Metrics/Piipan.Metrics.Core/DataAccessObjects/ParticipantUploadDao.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/ParticipantDao.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/UploadDao.cs, participants/tests/Piipan.Participants.Core.IntegrationTests/ParticipantDaoTests.cs, participants/tests/Piipan.Participants.Core.IntegrationTests/UploadDaoTests.cs, shared/src/Piipan.Shared/Database/AzurePgConnectionFactory.cs, shared/src/Piipan.Shared/Database/BasicPgConnectionFactory.cs
- Return unopened connections from DB connection factories
- Wrap queries in `using` to dispose connections
- Lets Dapper manage opening and closing of one-off queries
Observed the issue by connecting to the database, running match queries, and using `select count(*) from pg_stat_activity;` to see any affect on the number of open connections. Prior to this change the number of open connections would climb after each query. With this change in place, the number is relatively stable (as expected).
Since all the `using` blocks affect indentation, hiding whitespace changes is helpful for review.
Closes #2499
=> Dispose DbConnections to allow connection pooling

.gitignore, iac/arm-templates/blob-storage.json, iac/arm-templates/function-storage.json, iac/create-metrics-resources.bash, iac/create-resources.bash, iac/env/tts/dev.bash
- Azure Storage sku to add region redundancy
- Changed to the activity monitor name, given that when the resources are changed to another region, the creation of the activity monitor will fail because it is a global resource. Added LOCATION as part of the name.
Explained on #891 and #892
This was tested on `tts/eth2` deployed to westus2
=> Added storage redundancy configuration. It close #891 and #892

CHANGELOG.md
Release 0.96 has been merged to `main`. This is to merge release/0.96 back to `dev` to include the CHANGELOG update.
Partially addresses #2446
=> Merge release 0.96 back to dev

dashboard/docs/dashboard.md, docs/iac.md, query-tool/docs/query-tool.md
- Update web apps docs
- Update IaC doc
Closes #2521
=> Update docs to specify required Node.js version

iac/env/tts/test.bash
Syncs `tts/test` with the [recent changes](https://github.com/18F/piipan/pull/2503) to `tts/dev`.
- Update region to westus2
- Add storage SKU variable
Closes #2526
=> Sync tts/test env file with tts/dev

docs/adr/0023-subsystem-unit-testing-strategy.md
Adds an ADR describing our approach to unit testing the primary subsystems.
Closes #1838 
~~- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)~~
~~- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)~~
~~- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)~~
~~- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)~~
=> Subsystem unit testing strategy ADR

docs/adr/0025-use-windows-operating-system-for-app-service-plans.md
Adds and ADR explaining our decision to use Windows under the hood for all App Service plans
Closes #1376
~- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)~
~- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)~
~- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)~
~- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)~
=> Add ADR for decision to use Windows-based App Service plans

CHANGELOG.md
Merging release v0.97 back to dev, to include CHANGELOG.md updates.
See note in https://github.com/18F/piipan/blob/dev/docs/releases.md#tagging-the-release
~- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)~
~- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)~
~- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)~
~- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)~
=> Release v0.97 back to dev

docs/source-guidelines.md
Mention adding a new source tree (project) to the subsystem solutions file.
I wasn't sure whether these instructions were up-to-date. If they are, we should mention adding any new projects to solutions files for build/test/deploy purposes.
=> Add instruction for new sources in repo

docs/openapi/generated/bulk-api/openapi.md, docs/openapi/generated/bulk-api/openapi.yaml, etl/docs/openapi/upload.yaml
Adds example value for Content-Length header for Bulk Upload API. 
Some of our examples from our generated API docs have been confusing users. It's tempting to copy/paste the cURL request examples from the docs. 
Currently, API requests with a Content Length header of 0 will silently fail, and it takes a little while to debug when that happens. I figured putting an example content length that's equal to the byte-size of our example csv file could alleviate that confusion, for now. 
I'm still exploring options for widdershins template updates, and may post separate PR's related to that.
=> add example value for content-length header

CHANGELOG.md
Merging release v1.0 back to dev, to include CHANGELOG.md updates.
See note in https://github.com/18F/piipan/blob/dev/docs/releases.md#tagging-the-release
~- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)~
~- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)~
~- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)~
~- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)~
=> Release v1.0 back to dev

CHANGELOG.md
Releasing v1.0.0.33 back to dev to include CHANGELOG updates.
Jira-NAC/192
=> Release v1.0.0.33 back to dev

dashboard/tests/Piipan.Dashboard.Tests/Piipan.Dashboard.Tests.csproj, dashboard/tests/Piipan.Dashboard.Tests/packages.lock.json, etl/tests/Piipan.Etl.Func.BulkUpload.Tests/Piipan.Etl.Func.BulkUpload.Tests.csproj, etl/tests/Piipan.Etl.Func.BulkUpload.Tests/packages.lock.json, match/tests/Piipan.Match.Core.Tests/Piipan.Match.Core.Tests.csproj, match/tests/Piipan.Match.Core.Tests/packages.lock.json, match/tests/Piipan.Match.Func.Api.Tests/Piipan.Match.Func.Api.Tests.csproj, match/tests/Piipan.Match.Func.Api.Tests/packages.lock.json, participants/tests/Piipan.Participants.Core.IntegrationTests/Piipan.Participants.Core.IntegrationTests.csproj, participants/tests/Piipan.Participants.Core.Tests/Piipan.Participants.Core.Tests.csproj, participants/tests/Piipan.Participants.Core.Tests/packages.lock.json, query-tool/src/Piipan.QueryTool/Pages/Index.cshtml, query-tool/tests/Piipan.QueryTool.Tests/Piipan.QueryTool.Tests.csproj, query-tool/tests/Piipan.QueryTool.Tests/packages.lock.json, shared/tests/Piipan.Shared.Tests/Piipan.Shared.Tests.csproj, shared/tests/Piipan.Shared.Tests/packages.lock.json
To update dependencies, ran the 5 steps on the following link:
https://github.com/18F/piipan/blob/dev/docs/update-deps.md#semi-automated-steps 
on the following directories:
https://github.com/18F/piipan/pulls?q=is%3Apr+is%3Aopen+coverlet.collector 
Fix these dependabot findings:
https://github.com/18F/piipan/pulls?q=is%3Apr+is%3Aopen+coverlet.collector
-All automated updates from running the 5 step's commands
-A space in the index was added in order to commit again after having trouble pushing to github due to git bash GFE issues
##Extra Notes
Adding Bill and Michael as reviewers. With this being first time PR I wouldn't be surprised if something is wrong. Please feel free to let me know if anything needs to be changed or fixed
=> Coverlet collector updates

match/ddl/match-record.sql, match/tests/Piipan.Match.Core.IntegrationTests/DbFixture.cs, match/tests/Piipan.Match.Func.Api.IntegrationTests/DbFixture.cs
Adds `match_res_events` table schema to collaboration ddl
Relates to Jira NAC-165
This is the first step in implementing [match resolution events](https://github.com/18F/piipan/blob/dev/docs/adr/0027-use-event-sourcing-for-match-resolution.md) based on [our decision on how to sequence this work](https://github.com/18F/piipan/pull/2699#issuecomment-1048921838). 
Once this is merged, the next steps in implementing NAC-165 are to:
1. add a MatchResEventDao and Models to handle database queries for this table
1. add a MatchAggregator service to compile stateful data from match res events
1. use the Match Aggregator service to determine open/closed status in `MatchEventService.Reconcile`
These steps will be in the next PR.
=> Add match_res_events table

dashboard/src/Piipan.Dashboard/Startup.cs, query-tool/src/Piipan.QueryTool/Startup.cs
Fix on the startup.cs from the Query Tool and Dashboard App. The last scan does not detect the preload directive in the hsts configuration. [This comment](https://stackoverflow.com/questions/52046895/usehsts-not-working-with-netcore-2-1-website/56934285#56934285) suggests a solution that I tested on our Azure environment and it worked.
NAC-36
The scan reported that the duppartapi endpoint has not hsts active. Given that NAC-36 only includes Query Tool and Dashboard apps, I'm adding an additional issue for the duppartapi (APIM).
=> Fix preload for hsts on Query Tool and Dashboard

iac/apim-policy.xml
Added APIM policy for HSTS.
Security scanner finding (NAC-36)
It was tested in TTS environment.
=> Added hsts policy for APIM

iac/arm-templates/blob-storage.json, iac/arm-templates/function-storage.json
- Adds a dependency for each `storageAccounts/blobServices` resource on the associated parent `Microsoft.Storage/storageAccounts` resource
- Fixes issue where IaC will throw `ParentResourceNotFound` error when deploying to empty environments
Closes NAC-520
Adding @edwintorres for review and @ryangeorgeharvey for review/awareness
=> Update blob storage ARM templates to include dependency on parent

docs/iac.md, iac/create-resources.bash, match/docs/openapi/schemas/participant-record.yaml, match/docs/orchestrator-match.md, match/src/Piipan.Match/Piipan.Match.Api/Models/ParticipantMatch.cs, match/src/Piipan.Match/Piipan.Match.Core/Services/MatchEventService.cs, match/tests/Piipan.Match.Core.Tests/Builders/ActiveMatchRecordBuilderTests.cs, match/tests/Piipan.Match.Core.Tests/Services/MatchEventServiceTests.cs
The participant match record returned back from the Duplicate Participation API needs to return a MatchURL field, which should be populated with the associated Query Tool link.
This satisfies NAC-229
=> Added host name and match URL to the participant match record

iac/apim-policy.xml
Added hsts policy on error pages for the scanner.
NAC-36
=> Added hsts policy on errors

etl/tests/Piipan.Etl.Func.BulkUpload.IntegrationTests/DbFixture.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/DateRangeListHandler.cs, participants/tests/Piipan.Participants.Core.Tests/DateRangeListHandlerTests.cs, shared/src/Piipan.Shared/Utilities/DateRange.cs, shared/tests/Piipan.Shared.Tests/Utilities/DateRangeTests.cs
- Use inclusive bounding for both upper and lower bounds when setting database value
- Check bound inclusion property when parsing database values to DateRange instances
- Use Dapper in ETL db fixture to remove custom bound parsing
- Additional unit tests for DateRangeListHandler for value parsing / setting
Only changes to `DateRange.cs` were small updates to the documentation comments, but Omnisharp picked up some whitespace edits that make it look like more.
NAC-542
Sets the stage for using Npgsql's NodaTime extension when writing complex `daterange[]` values in a `COPY` statement
@kcherukupalli Tagging you for review since this builds on your recent work.
@bgfoshay …
=> Adjustments to DateRange bound handling

docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, match/docs/openapi/orchestrator/find.yaml, match/docs/openapi/schemas/participant-record.yaml
Adding the Match URL field to the generated API documentation, as well as updating the links to point to example domains.
Closes NAC-554
=> Updating readme and schemas for the new Match URL field

docs/openapi/generated/bulk-api/openapi.md, docs/openapi/generated/bulk-api/openapi.yaml, etl/docs/openapi/upload.yaml
- Renames `operationId` for `upload` endpoint. Previous value was the same as the value for `upload_all_participants`, causing only the `upload` endpoint to appear in the docs.
- Adds message to `upload` endpoint stating that it is deprecated and will be removed.
Follow-on to #3075. Now that `uploadAllParticipants.yaml` exists, just a couple tweaks to get the new endpoint to show up in the documentation and clarify the old endpoint has been deprecated.
=> Add `upload_all_participants` endpoint to public-facing docs

etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/packages.lock.json, etl/tests/Piipan.Etl.Func.BulkUpload.Tests/ParticipantTests.cs, etl/tests/Piipan.Etl.Func.BulkUpload.Tests/packages.lock.json, match/src/Piipan.Match/Piipan.Match.Func.Api/packages.lock.json, match/tests/Piipan.Match.Func.Api.IntegrationTests/packages.lock.json, match/tests/Piipan.Match.Func.Api.Tests/packages.lock.json, participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/ParticipantDao.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/Piipan.Participants.Core.csproj, participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs, participants/tests/Piipan.Participants.Core.Tests/packages.lock.json
- Use `COPY` (via `PostgreSQLCopyHelper`) to improve performance of writing large participant uploads to database
- Increase timeout duration for participant upload transaction to accomodate large uploads
- Introduce `Npgsql.NodaTime` plugin to handle setting the proper value for recent_benefit_issuance_dates field
NAC-556
@bgfoshay I made some tweaks from the proof-of-concept branch we'd be working on. The primary change is using `PostgreSQLCopyHelper` to abstract away some of the complexity of writing individual rows/values. I think the benefit from a developer's …
=> Use COPY for bulk inserting participant records

docs/openapi/generated/duplicate-participation-api/openapi.md, docs/openapi/generated/duplicate-participation-api/openapi.yaml, match/docs/openapi/schemas/match-query.yaml, match/src/Piipan.Match/Piipan.Match.Api/Models/OrchMatchRequest.cs, match/src/Piipan.Match/Piipan.Match.Core/Parsers/OrchMatchRequestParser.cs, match/tests/Piipan.Match.Core.Tests/Builders/ActiveMatchRecordBuilderTests.cs, match/tests/Piipan.Match.Core.Tests/Parsers/OrchMatchRequestParserTests.cs
Adding vulnerable_individual as an optional parameter to match api
https://e-jira.fns.usda.net/jira-prod/browse/NAC-98
API Doc updates to all params example, and match api 
comments on new code
tests for all cases and null case
generated docs
the checking of the vulnerable individual is not in the validator because it is still accepted if it is not valid
the manual checking of yes no and blank is because this will most likely never change and therefore doesn't need an enum
=> adding vulnerable individual to match api

.circleci/config.yml
Frontend tests require some initial node configuration that was not compatible with the updated `dotnet/sdk6.0` image. Resolution is to install node from a newer version supported by the image. Also dropped unnecessary `libappindicator1` package.
Nightly frontend tests in CircleCI are failing.
@bgfoshay No need to try and sneak this into this sprint's release if it's too late. Just …
=> Update CircleCI frontend tests for dotnet/sdk:6.0 container

query-tool/src/Piipan.QueryTool/Pages/Index.cshtml.cs
Due to search reason being required, the query tool needs to pass a value for search reason. Just passing "other" for now, we will be adding a search reason field at some point.
Otherwise the search cannot be performed
=> Added search reason to query tool when finding matches

docs/adr/0031-use-postgres-copy-for-bulk-upload.md
Conversations about the change to using `COPY` surfaced a need to update the associated ADR to include references to any PostgreSQL-specific code changes. Goal is to provide breadcrumbs for developers if/when making changes to the database system used for storing participant records.
Completes NAC-602
=> Update COPY ADR to reference PostgreSQL-specific code changes

components/src/Piipan.Components.Demo/Models/InputSSNModel.cs, components/src/Piipan.Components.Demo/Models/InputTextModel.cs, components/src/Piipan.Components.Demo/Pages/Index.razor, components/src/Piipan.Components.Demo/wwwroot/models/InputSSNModel.txt, components/src/Piipan.Components.Demo/wwwroot/models/InputTextModel.txt, components/src/Piipan.Components.Demo/wwwroot/sass/custom/_component_styles.scss, components/src/Piipan.Components/Forms/UsaForm.razor, components/src/Piipan.Components/Forms/UsaFormGroup.razor, components/src/Piipan.Components/Validation/UsaNameAttribute.cs, components/src/Piipan.Components/Validation/UsaSSNAttribute.cs, components/src/Piipan.Components/Validation/ValidationConstants.cs, components/tests/Piipan.Components.Tests/Input/UsaFormTests.razor, components/tests/Piipan.Components.Tests/Validation/UsaNameAttributeTests.cs, match/tests/Piipan.Match.Core.Tests/Services/MatchServiceTests.cs, query-tool/src/Piipan.QueryTool.Client/Components/QueryForm.razor, query-tool/src/Piipan.QueryTool.Client/Models/MatchSearchRequest.cs, query-tool/src/Piipan.QueryTool.Client/Models/PiiRecord.cs, query-tool/src/Piipan.QueryTool/wwwroot/sass/custom/_component_styles.scss, query-tool/tests/Piipan.QueryTool.Tests/Components/MatchFormTests.cs, query-tool/tests/Piipan.QueryTool.Tests/Components/QueryFormTests.cs, query-tool/tests/Piipan.QueryTool.Tests/MatchTest.cs
It was decided that if there were multiple errors with a certain field, we would show all of the errors instead of just the first one. In addition, the wording for when the user doesn't type in any letters is confusing, as it said "Normalized Last Name must be at least 1 character long." Now, we'll just say "Last Name must start with a letter" and update the requirements for that field appropriately.
- The UsaSSN attribute validation now returns all errors instead of just the first one
- The UsaName attribute now just simply checks to make sure the first non-space character they've typed is a letter
- The alert box was updated to show all errors on multiple list items when the returned error has more than one line
- The error above the field on a form was updated to show all errors …
=> Updates to Query Tool errors

docs/iac.md, query-tool/src/Piipan.QueryTool/package-lock.json
@ryangeorgeharvey and @kcherukupalli noticed that they were getting npm install errors for the query tool project. I was not getting any issues until I downgraded to node version 14.19.1, which is the same version that they were on and what Azure CloudShell was using.
The package-lock file was rebuilt with node version 14.19.1, and no longer has any issues.
Build issues described above
=> Updating package lock using a different node version

iac/arm-templates/front-door-app-service.json
The Strict-Transport-Security and X-Frame-Options headers were sometimes missing from the query tool and dashboard application due to Front Door/EasyAuth quirks. The easiest and most straightforward solution is to make changes to Front Door itself to pass these header values in the response.
Closes NAC-477, NAC-458, and NAC-505
=> Front door ARM Template changes for Security Headers

docs/openapi/bulk-api.yaml, docs/openapi/generated/bulk-api/openapi.md, docs/openapi/generated/bulk-api/openapi.yaml, etl/docs/openapi/uploadAllParticipants.yaml, iac/apim-bulkupload-policy.xml
Returning upload_id in upload api now with correct formatting
NAC-414
=> CJC-414 With Formatting

iac/create-resources.bash
ETL process requires increased timeout durations to avoid exceptions during long-running bulk load operations. These settings had previously been mistakenly applied to the connection string used by the Orchestrator function app rather than the ETL function app.
I re-ran IaC to confirm the ETL app is configured with the proper settings and the Orchestrator app is reverted to the default settings it used previously.
Fixing misconfiguration introduced by #2994.
=> Use increased database timeout settings for ETL

etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/Parsers/ParticipantStreamCsvParser.cs, etl/tests/Piipan.Etl.Func.BulkUpload.Tests/Parsers/ParticipantCsvStreamParserTests.cs, perf-tests/src/Etl.BulkUpload.Performance.TestRunner/BulkUploadPerfTestRunner.cs, perf-tests/src/Etl.BulkUpload.Performance.TestRunner/Etl.BulkUpload.Performance.TestRunner.csproj, perf-tests/src/Etl.BulkUpload.Performance.TestRunner/Program.cs
Fixes to Perf Test Runner to account for recent schema changes. Updated tooling to be strongly-typed to avoid schema changes unknowingly breaking it in the future.
NAC-703
=> Make Bulk Upload Perf test more strongly typed

match/src/Piipan.Match/Piipan.Match.Api/IMatchResolutionApi.cs, match/src/Piipan.Match/Piipan.Match.Api/Models/Resolution/MatchResListApiResponse.cs, match/src/Piipan.Match/Piipan.Match.Api/Models/Resolution/MatchResRecord.cs, match/src/Piipan.Match/Piipan.Match.Client/MatchResolutionClient.cs, match/src/Piipan.Match/Piipan.Match.Core/Builders/MatchResAggregator.cs, match/src/Piipan.Match/Piipan.Match.Core/DataAccessObjects/IMatchRecordDao.cs, match/src/Piipan.Match/Piipan.Match.Core/DataAccessObjects/IMatchResEventDao.cs, match/src/Piipan.Match/Piipan.Match.Core/DataAccessObjects/MatchRecordDao.cs, match/src/Piipan.Match/Piipan.Match.Core/DataAccessObjects/MatchResEventDao.cs, match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/AddEventApi.cs, match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/BaseApi.cs, match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/GetMatchApi.cs, match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/GetMatchesApi.cs, match/src/Piipan.Match/Piipan.Match.Func.ResolutionApi/GetMatchesListApi.cs, match/tests/Piipan.Match.Client.Tests/MatchResolutionClientTests.cs, match/tests/Piipan.Match.Core.IntegrationTests/MatchRecordDaoTests.cs, match/tests/Piipan.Match.Core.IntegrationTests/MatchResEventDaoTests.cs, match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/GetMatchApiIntegrationTests.cs, match/tests/Piipan.Match.Func.ResolutionApi.IntegrationTests/GetMatchesApiIntegrationTests.cs, match/tests/Piipan.Match.Func.ResolutionApi.Tests/GetMatchesApiTests.cs, match/tests/Piipan.Match.Func.ResolutionApi.Tests/GetMatchesListApiTests.cs, query-tool/src/Piipan.QueryTool.Client/Components/MatchesList.razor, query-tool/src/Piipan.QueryTool/Pages/BasePageModel.cs, query-tool/src/Piipan.QueryTool/Pages/List.cshtml, query-tool/src/Piipan.QueryTool/Pages/List.cshtml.cs, query-tool/src/Piipan.QueryTool/Pages/Shared/_Layout.cshtml, query-tool/src/Piipan.QueryTool/cypress/integration/match-list.spec.js, query-tool/tests/Piipan.QueryTool.Tests/Components/MatchesListTests.razor, query-tool/tests/Piipan.QueryTool.Tests/ListTest.cs
We need to add an API endpoint in the Match Resolution API Azure Function to get all of the existing matches. We then need to display these matches on a page in the Query Tool web application.
Closes NAC-169
=> Adding new API endpoint for getting all of the matches and corresponding View

query-tool/docs/query-tool.md, query-tool/src/Piipan.QueryTool/Pages/BasePageModel.cs, query-tool/src/Piipan.QueryTool/Pages/Error.cshtml.cs, query-tool/src/Piipan.QueryTool/Pages/Match.cshtml.cs, query-tool/src/Piipan.QueryTool/Pages/NotAuthorized.cshtml, query-tool/src/Piipan.QueryTool/Pages/NotAuthorized.cshtml.cs, query-tool/src/Piipan.QueryTool/appsettings.json, query-tool/src/Piipan.QueryTool/mock_user.json, query-tool/tests/Piipan.QueryTool.Tests/BasePageTest.cs, query-tool/tests/Piipan.QueryTool.Tests/ErrorTest.cs, query-tool/tests/Piipan.QueryTool.Tests/IndexTest.cs, query-tool/tests/Piipan.QueryTool.Tests/ListTest.cs, query-tool/tests/Piipan.QueryTool.Tests/MatchTest.cs, query-tool/tests/Piipan.QueryTool.Tests/NotAuthorizedPageTests.cs, shared/src/Piipan.Shared/Authorization/IgnoreAuthorizationAttribute.cs, shared/src/Piipan.Shared/Authorization/IgnoreNACAuthorizationAttribute.cs, shared/src/Piipan.Shared/Claims/ClaimsOptions.cs, shared/src/Piipan.Shared/Claims/ClaimsProvider.cs, shared/src/Piipan.Shared/Claims/IClaimsProvider.cs, shared/tests/Piipan.Shared.Tests/Claims/ClaimsProviderTests.cs
We are adding basic role and location based authorization to the Query Tool. After logging in, the logged in user must have a value for the location and also a value for their role in the NAC. If they don't we will redirect them to an unauthorized page.
In the future we will use the values of these claims to show/hide certain portions of the app based on these values, or when searching for a match we will pull in the initiating state from their location.
Closes NAC-413
=> Creating role-based authorization for the query tool

etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/BulkUpload.cs, etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/Parsers/ParticipantStreamCsvParser.cs, etl/src/Piipan.Etl/Piipan.Etl.Func.BulkUpload/Startup.cs, etl/tests/Piipan.Etl.Func.BulkUpload.Tests/BulkUploadTests.cs, iac/create-resources.bash, iac/iac-common.bash, participants/src/Piipan.Participants/Piipan.Participants.Api/IParticipantApi.cs, participants/src/Piipan.Participants/Piipan.Participants.Api/Models/ParticipantUploadErrorDetails.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/Extensions/ServiceCollectionExtensions.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/Models/ParticipantUploadErrorDetails.cs, participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs, participants/tests/Piipan.Participants.Core.IntegrationTests/ParticipantServiceTests.cs, participants/tests/Piipan.Participants.Core.Tests/Extensions/ServiceCollectionExtensionsTests.cs, participants/tests/Piipan.Participants.Core.Tests/Services/ParticipantServiceTests.cs, shared/src/Piipan.Shared/Deidentification/IRedactionService.cs, shared/src/Piipan.Shared/Deidentification/RedactionService.cs, shared/tests/Piipan.Shared.Tests/Deidentification/RedactionServiceTests.cs
When the participant upload gets changed to "Failed", we should be logging information about the file so that we can try to identify what caused the upload to fail.
Per NAC-577, that data includes:
- State that uploaded
- Timestamp of upload processing start
- Timestamp of upload processing fail
- Error and location of the error (eg. stacktrace)
- Name of failed file
We also need to redact out any PII (LDS Hash, Participant ID, Case Number) from the error text or file name. A redaction service was created for this purpose.
A small IAC change was created to add the State to the Bulk Upload Azure Function. We could have gotten this information from the database connection string, but it seemed quite hacky, so I figured adding it as a configuration setting would be the best bet.
Closes …
=> Participant upload error logging

dashboard/src/Piipan.Dashboard/package-lock.json, dashboard/tests/Piipan.Dashboard.Tests/PackageLockTests.cs, query-tool/src/Piipan.QueryTool/package-lock.json, query-tool/tests/Piipan.QueryTool.Tests/PackageLockTests.cs
Removing the peer dependencies from the package-lock file that caused npm install to break when building a project.
Also added a couple test cases to make sure that the peer dependencies do not exist.
Developers were getting errors building the dashboard and query tool projects.
=> Removing conflicting Peer Dependencies that cause npm install to break

query-tool/src/Piipan.QueryTool/cypress/integration/match-list.spec.js, query-tool/src/Piipan.QueryTool/cypress/integration/match-query.spec.js, query-tool/src/Piipan.QueryTool/cypress/integration/participant-query.spec.js
We don't have a way to call API calls yet from the nightly build. Full end-to-end testing is desired in the future, but will be a significant effort. Therefore we will just comment out the pa11y tests for now that rely on the API calls.
Closes NAC-791
=> Commenting out pa11y tests that depend on API calls

participants/src/Piipan.Participants/Piipan.Participants.Core/Services/ParticipantService.cs, participants/tests/Piipan.Participants.Core.Tests/Services/ParticipantServiceTests.cs
Per comments made by @kingcomma, we should have a better test in the participant service tests that shows we can handle the actual redaction of an exception instead of just a mock.
Also after our discussion we noticed that if the error was due to the parsing and not the upload, that the parsing would continue to fail in the error logging. Thus we should catch any parsing errors and still redact the information that we were previously able to parse.
Fixes concerns for NAC-577
=> Updated Participant Service tests to include a better exception test with the redaction serve

CHANGELOG.md, docs/adr/0023-subsystem-unit-testing-strategy.md, docs/engineering-team-practices.md
Across three `*.md` files correct misspelings.
| Misspelling | Fix | File|
| -- | -- | -- |
| esponses | responses | CHANGELOG.md |
| accomodate | accommodate | CHANGELOG.md |
| depenencies | dependencies | docs/adr/0023-subsystem-unit-testing-strategy.md |
| Architectual | Architectural | docs/engineering-team-practices.md |
| Asignee | Assignee | docs/engineering-team-practices.md |
Misspellings.
=> Misspelling Corrections

query-tool/docs/query-tool.md, query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetail.razor, query-tool/src/Piipan.QueryTool/Pages/Match.cshtml, query-tool/src/Piipan.QueryTool/Pages/Match.cshtml.cs, query-tool/src/Piipan.QueryTool/Startup.cs, query-tool/src/Piipan.QueryTool/appsettings.json, query-tool/tests/Piipan.QueryTool.Tests/BasePageTest.cs, query-tool/tests/Piipan.QueryTool.Tests/Components/MatchDetail/MatchDetailTests.razor, query-tool/tests/Piipan.QueryTool.Tests/MatchTest.cs, shared/src/Piipan.Shared/Roles/IRolesProvider.cs, shared/src/Piipan.Shared/Roles/RoleOptions.cs, shared/src/Piipan.Shared/Roles/RolesProvider.cs, shared/tests/Piipan.Shared.Tests/Roles/RolesProviderTests.cs
The edit section of the Match Detail page should only be shown to users with certain roles (see NAC-501).
The roles that are able to edit the Match Detail page will be configurable via the appsettings.json. For development purposes, we are allowing users with the role of "Worker".
Closes NAC-501
=> Showing/Hiding Match Detail edit section based off user's role

CHANGELOG.md
- Add 1.1.1 note back in (was clobbered by retroactive reverts and merges)
- Update subsequent releases to use 1.1.1.x versioning
- Add links for past several releases that did not have them
CHANGELOG got out of whack during all the work for merging v1.1.1 and subsequent releases. Closes NAC-1049.
=> Update CHANGELOG using consistent versioning for 1.1.1.x releases

components/src/Piipan.Components.Demo/Components/TooltipComponent.razor, components/src/Piipan.Components.Demo/Pages/Index.razor, components/src/Piipan.Components.Demo/Pages/Tooltip.razor, components/src/Piipan.Components.Demo/Shared/NavMenu.razor, components/src/Piipan.Components.Demo/wwwroot/components/TooltipComponent.txt, components/src/Piipan.Components/Piipan.Components.csproj, components/src/Piipan.Components/Tooltips/UsaTooltip.razor, components/src/Piipan.Components/Tooltips/UsaTooltip.razor.css, components/src/Piipan.Components/Tooltips/UsaTooltip.razor.js, components/tests/Piipan.Components.Tests/Tooltips/UsaTooltipTests.razor, query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/VulnerableInvalidStatus.razor, query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/VulnerableInvalidStatus.razor.css, query-tool/tests/Piipan.QueryTool.Tests/Components/MatchDetail/VulnerableInvalidStatusTests.razor
A Blazor tooltip component is added to the Component Library, allowing us to easily put a tooltip on any item. We then add it to the Match Detail page, on the Invalid Match and Vulnerable Individual parts of the screen.
Closes NAC-445
=> Adding tooltip component and adding it to Match Details

iac/arm-templates/dashboard-app.json, iac/arm-templates/query-tool-app.json
Setting HttpsOnly to true to make it so HTTP always redirects to HTTPS for Dashboard and Query Tool app service.
Closes NAC-32
=> HTTPS only flipped to true for dashboard and query tool

iac/db-common.bash
Added parameter with the table name to two functions on db_common to assign access level. This third parameter is optional, the default value is ALL TABLES. 
NAC-944 Add additional functionality to support adding different levels of access at the table-level. For example, authorizing the state metadata API to only have access to the state_info table and no other tables in the collaboration database
=> NAC-944: Added third parameter for table name with default value

match/tools/test-apim-match-api.bash
Adds required `participant_id` field to request body in `test-apim-match-api.bash`. Verify changes by running: `./match/tools/test-apim-match-api.bash <env>`.
NAC-1047; Smoke test does not function as intended without the required field.
=> Add required participant_id field to match API test script

query-tool/src/Piipan.QueryTool.Client/Components/MatchDetail/MatchDetailWrapper.razor, query-tool/src/Piipan.QueryTool.Client/Components/QueryForm.razor, query-tool/tests/Piipan.QueryTool.Tests/Components/MatchDetail/MatchDetailWrapperTests.razor, query-tool/tests/Piipan.QueryTool.Tests/Components/QueryFormTests.cs
Due to the Unauthorized Banner PR (https://github.com/18F/piipan/pull/3663), a couple of bugs were introduced for users that did have correct permissions. While the focus was hiding/disabling things for users without permissions, sufficient unit tests and manual testing was not done for users that had permissions. @kcherukupalli found these errors during his development, and these fixes should take care of them. Unit tests added as well for these scenarios.
Fixes bugs introduced as part of https://github.com/18F/piipan/pull/3663
=> Fixing a couple permission-based bugs

dashboard/src/Piipan.Dashboard.Client/Components/ParticipantUploads/ParticipantUploads.razor, dashboard/src/Piipan.Dashboard.Client/Components/ParticipantUploads/ParticipantUploadsFilter.razor, dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml, dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml.cs, dashboard/tests/Piipan.Dashboard.Tests/Components/ParticipantUploads/ParticipantUploadsFilterTests.razor, dashboard/tests/Piipan.Dashboard.Tests/Components/ParticipantUploads/ParticipantUploadsTests.razor, dashboard/tests/Piipan.Dashboard.Tests/ParticipantUploadsModelTests.cs
Changing the metrics filter form to use GET instead of POST, so that the URL always accurately reflects the filter
_Link to specific issue (ex: Closes #123)_
=> Changed metrics filter form to a GET instead of POST
